### DISCUSSION TITLE
Permissions/ACL Errors in Built Tauri App

### DISCUSSION THREAD

**Discussion by zeller-lorenz** [tauri-apps/tauri#10933] [Q&A]
I've developed a Tauri application using several plugins. While the app functions correctly when run with npm run tauri dev, I encounter permission/ACL errors after building it with npm run tauri build.
### Current Behavior

1. `npm run tauri dev`: The application runs without any errors, and all plugins work as expected.

2. `npm run tauri build`: The built application produces the following errors:

![image](https://github.com/user-attachments/assets/9af6b1fc-9da7-4453-8a30-283623c15e22)

These errors prevent the plugins from functioning, which significantly impacts the application's core functionality.
### Expected Behavior
The built application should run without permission/ACL errors, and all plugins should function correctly, mirroring the behavior observed in the development environment.

Can anyone help me with this/had similar problems?

### Environment
- OS: macOS 15.0 - Sequoia 
- Tauri version: 2.0.0-rc
- Node.js version: v21.7.1
- npm version: 10.5.0

Here's my cargo.toml + the default.json for the plugin permissions:

```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "main_lib"
crate-type = ["lib", "cdylib", "staticlib"]


[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-rc", features = ["devtools"] }
tauri-plugin-fs = "2.0.0-rc"
#tauri-plugin-http = { version = "2.0.0-rc", features = [] }
tauri-plugin-os = "2.0.0-rc"
tauri-plugin-shell = { version = "2.0.0-rc", features = [] }
dirs = "5.0.1"
pnet = "0.35.0"
sha2 = "0.10.8"
rusqlite = {version = "0.32.1", features = ["bundled-sqlcipher", "serde_json"] }

[profile.release.package.wry]
debug = true
debug-assertions = true

```

```json
{
  "$schema": "../gen/schemas/macOS-schema.json",
  "identifier": "default",
  "description": "enables the default permissions",
  "windows": [
    "main"
  ],
  "permissions": [
    "core:app:default",
    "core:path:allow-resolve",
    "core:path:allow-resolve-directory",
    "core:window:default",
    "core:webview:default",
    "core:resources:default",
    "core:image:default",
    "core:menu:default",
    "core:tray:default",
    "core:path:allow-resolve-directory",
    "os:allow-hostname",
    {
      "identifier": "fs:allow-copy-file",
      "allow": [
        "**"
      ]
    },
    {
      "identifier": "fs:allow-exists",
      "allow": [
        {
          "path": "**"
        }
      ]
    },
    {
      "identifier": "fs:allow-remove",
      "allow": [
        "**"
      ]
    }
  ],
  "platforms": [
    "macOS",
    "windows"
  ]
}
```
