### DISCUSSION TITLE
How to cross-compile in GitLab CI? yarn✅ but npm❗err:   `unexpected argument 'cargo-xwin' found` /  `cargo-xwin command not found`

### DISCUSSION THREAD

**Discussion by lukasMega** [tauri-apps/tauri#11256] [Q&A] [answered]
Is there some example / template with `.gitlab-ci.yml`
I have found some but they requires windows machine.
I'm interested in using a generic Linux Docker GitLab Runner to build a Tauri app for multiple platforms (Windows x64, Linux, MacOS). Is this possible? Thank you in advance for your response.

solved in reply https://github.com/tauri-apps/tauri/discussions/11256#discussioncomment-10924424

**Comment by lukasMega** [comment]
> [!CAUTION]
> ## ``` failed to build app: `cargo-xwin` command not found.```
> - when: `./node_modules/.bin/tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`


I successfully configured CI pipeline to build the app with default output - linux binaries (simple hello world Tauri app)

Adding needed dependencies for cross compiling windows binaries - everything finished without problems except last step for - build command: https://v2.tauri.app/distribute/windows-installer/#building-the-app

I have tried commands:
 - `npm run tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`
 - `tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`
 - `./node_modules/.bin/tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`

**my output:**

```console

$ cargo xwin --version
cargo-xwin-xwin 0.17.3

$ ./node_modules/.bin/tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
    Running beforeBuildCommand `npm run build`
> app-mgr@0.1.0 build
> tsc && vite build
vite v5.4.8 building for production...
transforming...
✓ 10 modules transformed.
rendering chunks...
computing gzip size...
dist/index.html                  0.45 kB │ gzip: 0.29 kB
dist/assets/index-DR98o5Jx.css   1.37 kB │ gzip: 0.65 kB
dist/assets/index-DMajhg5x.js   14.24 kB │ gzip: 5.91 kB
✓ built in 373ms
failed to build app: `cargo-xwin` command not found.
    Error failed to build app: `cargo-xwin` command not found.

```

any advice? Thank you in advance


My environment:

```console

Running with gitlab-runner 17.4.0 (b92ee590)
  on runner2-dind zZzivAWtV, system ID: r_U4tjkWvpfQV5
Preparing the "docker" executor 00:02
Using Docker executor with image cimg/rust:1.81-node ...
Pulling docker image cimg/rust:1.81-node ...

$ node -v ; npm -v && rustc --version && cargo --version || echo '';
v20.17.0
10.8.2
rustc 1.81.0 (eeb90cda1 2024-09-04)
cargo 1.81.0 (2dbb1af80 2024-08-20)

```

**Reply by lukasMega** [reply]
> [!Caution]
> ## ```error: unexpected argument 'cargo-xwin' found```
> - when: `npm run tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`

```console
$ cargo xwin --version
cargo-xwin-xwin 0.17.3
$ npm run tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc || { echo "❗ previous command failed"; }
> app-mgr@0.1.0 tauri
> tauri build cargo-xwin x86_64-pc-windows-msvc
    Running beforeBuildCommand `npm run build`
> app-mgr@0.1.0 build
> tsc && vite build
vite v5.4.8 building for production...
transforming...
✓ 10 modules transformed.
rendering chunks...
computing gzip size...
dist/index.html                  0.45 kB │ gzip: 0.29 kB
dist/assets/index-DR98o5Jx.css   1.37 kB │ gzip: 0.65 kB
dist/assets/index-DMajhg5x.js   14.24 kB │ gzip: 5.91 kB
✓ built in 382ms
error: unexpected argument 'cargo-xwin' found
Usage: cargo build [OPTIONS]
For more information, try '--help'.
failed to build app: failed to build app
    Error failed to build app: failed to build app
❗ previous command failed
```

**Comment by nakedgremlin** [comment]
@lukasMega I'm was researching how to craft a GitLab CI for a Windows build and came across this thread.

Here is my solution for a GitLab CI YML, maybe it'll help you on your cargo issues.

```yml
build windows installer:
  image: ivangabriele/tauri:debian-bookworm-20
  stage: build
  environment: staging
  before_script:
    - cd app # wherever your source is
    - apt-get -y install nsis # This was needed to resolve a packaging issue
    - apt-get -y install clang # Had to add to resolve a dialog issue on launch
    - apt-get -y install lld llvm
    - rustup target add x86_64-pc-windows-msvc # Install the 64-bit target
    - cargo install --locked --quiet cargo-xwin # Install cargo-xwin
    - yarn install --frozen-lockfile # Install app dependencies
  script:
    - yarn build-windows # Build for Windows 64-bit target
    # This is a shortcut command in my package.json that does the following:
    # tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
```

This gets you a Windows x64 installer EXE at this location:
- `app/src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/`

I did use a specific image that I found that contains a lot of the pre-built libraries to help streamline this build process. Maybe toggling over to that image might help your build issues.

I hope that helps.

**Reply by nakedgremlin** [reply]
I updated the above to include:
```yaml
    - apt-get -y install clang
    - apt-get -y install lld llvm
```

To resolve some Windows launch issue that surfaced related to a Windows launch issue after installation

**Reply by lukasMega** [reply]
Thank you for your input @nakedgremlin !
I have tried that docker image you suggested.
Unfortunately I’m getting the same error:
`error: unexpected argument 'cargo-xwin' found`

Only difference is that i’m using npm, i will try yarn instead and we will see…
https://github.com/user-attachments/assets/abb62490-3c8c-4d5d-b5a5-0f62605c70e8


Also i will try to delete caches again.

// UPDATE:
I just realized that probably cargo/rust related commands (`rustup target add x86_64-pc-windows-msvc` and `cargo install --locked --quiet cargo-xwin`) needs to be executed in the `src-tauri` folder where the `Cargo.toml` is located
(FYI: I'm totally new and lost in Rust ecosystem)

// UPDATE-2:
Still the same error, also when I deleted runner caches and when executed cargo install in `src-tauri` folder

**Reply by lukasMega** [reply]
I will try another docker image, which is mentioned here: https://github.com/tauri-apps/tauri/discussions/9650#discussioncomment-10912246

**Reply by lukasMega** [reply]
Still the same error with cargo-xwin:
``` error: unexpected argument 'cargo-xwin' ```

Here is example repo and full log:
- https://gitlab.com/lukasMega/tauri-sample-v2/-/jobs/8066937244

**Comment by lukasMega** [comment]
I have tried 3 different docker images for building Tauri helloworld sample app:
 - 📦  repo with MRE (Minimal, Reproducible Example): https://gitlab.com/lukasMega/tauri-sample-v2
   - created using command: `npm create tauri-app@latest` yesterday
 - 🚀  used command: `npm run tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`

## 1. `ivangabriele/tauri:debian-bookworm-20`

CI output: https://gitlab.com/lukasMega/tauri-sample-v2/-/jobs/8069329620#L572

<details><summary>click to see environment output:</summary>

```console
$ rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
$ cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
$ cargo xwin --version
cargo-xwin-xwin 0.17.3
$ node -v && npm -v
v20.18.0
10.8.2
$ echo $PATH && pwd
/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/builds/lukasMega/tauri-sample-v2
$ npm run tauri info
> tauri-app@0.1.0 tauri
> tauri info
[✔] Environment
    - OS: Debian 12.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.81.0-x86_64-unknown-linux-gnu (default)
    - node: 20.18.0
    - pnpm: 9.12.1
    - npm: 10.8.2
[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2
[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0
[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite

```
</details>





## 2. `cimg/rust:1.81-node`

CI output: https://gitlab.com/lukasMega/tauri-sample-v2/-/jobs/8069329625#L2433

<details><summary>click to see environment output:</summary>

```console
$ rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
$ cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
$ cargo xwin --version
cargo-xwin-xwin 0.17.3
$ node -v && npm -v
v20.17.0
10.8.2
$ echo $PATH && pwd
/home/circleci/.cargo/bin:/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/builds/lukasMega/tauri-sample-v2
$ npm run tauri info
> tauri-app@0.1.0 tauri
> tauri info
[✔] Environment
    - OS: Ubuntu 22.4.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.81.0-x86_64-unknown-linux-gnu (default)
    - node: 20.17.0
    - yarn: 1.22.19
    - npm: 10.8.2
[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2
[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0
[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```
</details>



## 3. `websmurf/tauri-builder:1.0.3`

CI output: https://gitlab.com/lukasMega/tauri-sample-v2/-/jobs/8069329630#L123

<details><summary>click to see environment output:</summary>

```console
$ rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
$ cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
$ cargo xwin --version
cargo-xwin-xwin 0.17.3
$ node -v && npm -v
v20.18.0
10.8.2
$ echo $PATH && pwd
/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/builds/lukasMega/tauri-sample-v2
$ npm run tauri info
> tauri-app@0.1.0 tauri
> tauri info
[✔] Environment
    - OS: Debian 12.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.18.0
    - yarn: 1.22.22
    - npm: 10.8.2
[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2
[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0
[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```
</details>

---

output for every case:

> [!Caution]
> ## ```error: unexpected argument 'cargo-xwin' found```
> - when: `npm run tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc`


Am I doing something wrong? Or is there an incompatibility between some versions ?

**Reply by lukasMega** [reply, marked as answer]
after 5 days, I tried change `npm` to `yarn` and it helped. First successful build: https://gitlab.com/lukasMega/tauri-sample-v2/-/jobs/8070254109 🎉 
I have used nearly the same code as @nakedgremlin provided above https://github.com/tauri-apps/tauri/discussions/11256#discussioncomment-10909210

<details> <summary> the code working </summary>

```yaml
###
### example by @nakedgremlin (https://github.com/tauri-apps/tauri/discussions/11256#discussioncomment-10909210)
###  ♦️ yarn is used instead of npm
###
build windows installer:
  image: ivangabriele/tauri:debian-bookworm-20
  stage: build
  before_script:
    #- cd app # wherever your source is
    - apt-get -y install nsis # This was needed to resolve a packaging issue
    - apt-get -y install clang # Had to add to resolve a dialog issue on launch
    - apt-get -y install lld llvm
    - rustup target add x86_64-pc-windows-msvc # Install the 64-bit target
    - cargo install --locked --quiet cargo-xwin # Install cargo-xwin
    - yarn install --frozen-lockfile # Install app dependencies
  script:
    - yarn build-windows # Build for Windows 64-bit target
    # This is a shortcut command in my package.json that does the following:
    # tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
  artifacts:
    paths: ["src-tauri/target/x86_64-pc-windows-msvc/release/bundle"]

```

https://gitlab.com/lukasMega/tauri-sample-v2/-/blob/master/.gitlab-ci.yml?ref_type=heads#L35-56

</details>

Thank you !

### ❓ Anybody know more details why it's working with **yarn** and not with **npm**?
