### DISCUSSION TITLE
Environment variables and CI builds 😅

### DISCUSSION THREAD

**Discussion by bodeby** [tauri-apps/tauri#11810] [Q&A] [answered]
Hello Tauri Wizards,

I have a question about adding environment variables to a CI build. My build relies on several environment variables to function correctly.

Currently, I’ve added these values to my repository’s GitHub Secrets and Variables, and I was wondering if i could reference them during the frontend build like this:

````yml
- name: build frontend
    run: pnpm build
        env:
            var1: ${{ vars.vars1 }}
            var2: ${{ vars.vars2 }}
            sec1: ${{ secrets.sec1}}
`````

Current github action setup

````yml
      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: pnpm install # change this to npm or pnpm depending on which one you use.
`````

My question is: should I remove the configured `beforeBuildCommand` in `tauri.conf.json` and instead handle the frontend build explicitly in the CI workflow as shown above? Additionally, how would this change impact the development workflow, particularly the usage of `pnpm tauri` build during local development?

All insights on best practices are highly appreciated :blush:

**Note**: Workflow is taken from the official [documentation](https://v2.tauri.app/distribute/pipelines/github/) and the [action](https://v2.tauri.app/distribute/pipelines/github/)

### Full github actions for reference

````yml
name: "publish"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main # Trigger on PRs merging into the main branch

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm" # Set this to npm, yarn or pnpm.

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: pnpm install # change this to npm or pnpm depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
```````
