### DISCUSSION TITLE
Tailwindcss `env(safe-area-inset-bottom)` doesn't work on bottom navigation bar

### DISCUSSION THREAD

**Discussion by setoelkahfi** [tauri-apps/tauri#13099] [Q&A]
I've been trying to solve this iPhone issue with the bottom navigation bar and the top safe area being transparent with no luck.

https://github.com/user-attachments/assets/7fd9fe03-bbb8-48cc-a28b-13b72421da71

What I have tried:
- Using the env(safe-area-x) on tailwindcss side:
```css

@layer utilities {
  .pb-safe {
    padding-bottom: env(safe-area-inset-bottom);
  }
  .pt-safe {
    padding-top: env(safe-area-inset-top);
  }
}
```

- view-port:
```html
      <meta
        name="viewport"
        content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
      />
```
- I tried to reach out to the Swift code, but there's only one launch screen interface builder.

Any pointers?
