### DISCUSSION TITLE
http response - Fetch in tauri v2

### DISCUSSION THREAD

**Discussion by mohammadhasananisi** [tauri-apps/tauri#13603] [Q&A] [answered]
hi 
When I use fetch, I can't get the response, but I can see the code. What's the problem?

```js
import { fetch as tauriFetch } from '@tauri-apps/plugin-http';
    const response = await tauriFetch(fullUrl, fetchOptions);

    if (!response.ok) throw response;

    const responseData = await response.json();

    console.log(responseData);
```

It gets stuck when it reaches this line. ==>    const responseData = await response.json();

**Comment by FabianLars** [comment]
share the output of `tauri info` please. this _should_ be something related to the versions.

**Reply by mohammadhasananisi** [reply]
```toml
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = "2"
```
