### DISCUSSION TITLE
How can I use latest dev branch in my Tauri project?

### DISCUSSION THREAD

**Discussion by nothingismagick** [tauri-apps/tauri#2161] [Q&A]
Sometimes a fix hasn't propagated to a release yet, and you may have to actually pull in from git - or even clone the repo and perform some modification. While this isn't recommended for everyday use - sometimes there is no way to avoid it. What options are there for this?

**Comment by shirakaba** [comment]
The Tauri example apps give some basis for this. Instead of being pinned to a specific version of `tauri` and `tauri-build`, they are pinned to equivalent on-disk copies. See [examples/helloworld/src-tauri/Cargo.toml](https://github.com/tauri-apps/tauri/blob/dev/examples/helloworld/src-tauri/Cargo.toml):

```toml
[package]
name = "helloworld"
version = "0.1.0"
description = "A very simple Tauri Appplication"
edition = "2018"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = [ "codegen" ] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "../../../core/tauri", features = [] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
```

* `tauri` links off to [core/tauri/Cargo.toml](https://github.com/tauri-apps/tauri/blob/dev/core/tauri/Cargo.toml).
* `tauri-build` links off to [core/tauri-build/Cargo.toml](https://github.com/tauri-apps/tauri/blob/dev/core/tauri-build/Cargo.toml).

Each of those reference other dependencies of their own within the Tauri repo, and are already set up to do so via local paths.

Would this approach suffice? Or would there be sense in going one step further and providing a utility (maybe via the CLI) to generate a playground project that references a local clone of the Tauri repo (you'd just have to provide the path to it)?

**EDIT:** you can also set a remote git repository as a Cargo dependency, e.g.:

```toml
wry = { git ="https://github.com/tauri-apps/wry", branch = "feat/ios" }
```

... however, I don't know whether there are any limitations with that (there are in the world of npm); you'd need to be able to select a path other than the root of the repo, and I'm not sure whether Cargo supports that.
