### DISCUSSION TITLE
Mica Background in Tauri JS

### DISCUSSION THREAD

**Discussion by PacifiK2460** [tauri-apps/tauri#4747] [Q&A] [answered]
How can I enable the mica / blur background in Tauri JS?, I followed some threads here but can't get it working.

Deleteing / setting to transparent any css property about background results in a white background:
![image](https://user-images.githubusercontent.com/42554588/180866819-20581a3c-e018-4f82-aaf6-53ed7856a2fa.png)

> Cargo.toml

```toml
#...

[dependencies]
tauri = { version = "1.0.3", features = ["api-all"] }
window-vibrancy = "0.1.3"

#...
```

> main.rs

```rust
#[cfg(target_os = "windows")]
use window_vibrancy::{apply_mica, apply_blur};

//...

  let main_window = app.get_window("main").unwrap();
  #[cfg(target_os = "windows")]
  {
       apply_mica(&main_window)
                .expect("Unsupported platform! 'apply_mica' is only supported on Windows");
  }

//...
```

> tauri.conf.json
```js
"windows": [
  {
    "fullscreen": false,
    "height": 600,
    "resizable": true,
    "title": "Title",
    "width": 800,
    "visible": true,
    "transparent": true,
    "center": true
  }
```
