### DISCUSSION TITLE
Windows 7 err: The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll.

### DISCUSSION THREAD

**Discussion by XiaoBlank** [tauri-apps/tauri#5084] [Q&A] [answered]
err: `The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll.`
I created a simply app。in development computer, every thing is ok ( compile ok, run ok). then distributed as Windows 7 Installers (.msi files). setup successed. but  run app,an error occurred:
`The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll.`

-----------------------------------------------------------------------------

Development computer os:
windows 10, prerequisites According to the tauri Guides(https://tauri.app/v1/guides/getting-started/prerequisites)

-----------------------------------------------------------------------------

**Target OS: Windows 7**

-----------------------------------------------------------------------------
Windows 7  is  VM (Oracle VM VirtualBox)
```
View basic information about your computer
Windows edition
Windows 7 Ultimate N
Copyright  2009 Microsoft Corporation.All rights reserved. Service Pack1

System
Rating: System rating is not available 
Processor: Intel(R) Core(TM)i7-10510U CPU@1.80GHz2.30 GHz 
Installed memory (RAM): 2.00 GB
System type: 64-bit Operating System 
Pen and Touch: No Pen or Touch Input is available for this Display 
Computer name, domain, and workgroup settings
Computer name: test1-PC 
Full computer name: test1-PC 
Computer description:
Workgroup: WORKGROUP
```
------------------------------------------------

**Cargo.toml**
```toml
[package]
name = "demo1App"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"
 

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1", features = ["api-all", "windows7-compat"] }

[features] 
default = [ "custom-protocol" ] 
custom-protocol = [ "tauri/custom-protocol" ]
```
**tauri.conf.json (Webview2 Installation Options Fixed Version)**
```json
{
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist"
  },
  "package": {
    "productName": "demo1App",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "demo1.demo.com",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": "",
        "webviewInstallMode": {
          "type": "fixedRuntime",
          "path": "./Microsoft.WebView2.FixedVersionRuntime.104.0.1293.70.x64/"
        }
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "demo1App",
        "width": 800
      }
    ]
  }
}
```
**main.rs**
```rs
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

I had try Webview2 Installation other Options  (Offline Installer,Embedded Bootstrapper) . but can't fix this problem.

I  search the tauri guides documcent, issuess list  and disccusions,but not find any similarity solutions。
What things did I miss？
I'm looking forward to your help！
Thank you very much!
