### DISCUSSION TITLE
App does not run after installation .deb

### DISCUSSION THREAD

**Discussion by ghost** [tauri-apps/tauri#5735] [Q&A] [answered]
Built using Git Actions for Linux, Windows and MacOS

I downloaded the deb package and installed it, but it did not run

I decided to run it from terminal, it says this
```
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
What is the possible problem

git actions file 
```yaml
name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: install & build frontend
        run: yarn && yarn build

      - name: build 
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: 'Assets'
          releaseDraft: true
          prerelease: false
```
