### DISCUSSION TITLE
How to store credentials with tauri build

### DISCUSSION THREAD

**Discussion by GHGHGHKO** [tauri-apps/tauri#7438] [Q&A]
Hello! 

I want to store the API KEY that I have when running the `pnpm tauri build` command.

I'm trying to input the API KEY from workflows, for example:
```yml
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          TENOR_API_KEY: ${{ secrets.TENOR_API_KEY }}
```

However, after running `pnpm tauri build` and installing the files, it seems that the keys are not working.

This is my code:
```rust
    let giphy_key = env::var("GIPHY_API_KEY")
        .unwrap_or_else(|_| String::from(key));
```

I've looked at similar discussions, but I still don't understand.
Is there a solution to this issue?

Thank you always for your efforts.

full code : https://github.com/GHGHGHKO/dalgona
similar discussions : https://github.com/tauri-apps/tauri/discussions/1222
