### DISCUSSION TITLE
How do I make Tauri work on projects with multiple bins?

### DISCUSSION THREAD

**Discussion by m4heshd** [tauri-apps/tauri#7592] [Q&A]
My project has multiple bins. One of them is the Tauri client. But how do I tell Tauri which bin to worry about?

Here's what I have so far. This is how I do it on all the other Rust projects.

**Directory structure:**
```
.
└── src-tauri/
    └── src/
        ├── bin/
        │   ├── client/
        │   │   └── main.rs
        │   └── pack/
        │       └── main.rs
        ├── lib.rs
        ├── module_one.rs
        └── module_two.rs
```

**Cargo.toml:**
```toml
[[bin]]
name = "Client"
path = "src/bin/client/main.rs"

[[bin]]
name = "Pack"
path = "src/bin/pack/main.rs"
```

**package.json:**
```json
"scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "tauri-dev": "tauri dev -- --bin Client",
    "tauri-build": "tauri build -- --bin Client"
  }
```

This works fine when using `npm run tauri-dev` but `npm run tauri-build` fails with the following error.
```json
Error failed to bundle project: Failed to get main binary
```

How do I make Tauri treat the `Client` bin as its main binary?
