### DISCUSSION TITLE
When building with github CI, `rename` command uses wrong path for macos aarch64 target

### DISCUSSION THREAD

**Discussion by 39george** [tauri-apps/tauri#8311] [Q&A] [answered]
I'm trying to build releases using github CI here: https://github.com/olegus199/MDog/actions/runs/7003825406/job/19050313058,
I set up arch in workflow.yml:
```yaml
 - os: macos-latest
    target: aarch64-apple-darwin

# {..other settings here..}

- name: Build application
    run: pnpm tauri build -- --target ${{ matrix.target }} -v
```
But when rust build finished, there are some `rename` command fails:
<img width="754" alt="Screenshot 2023-11-27 at 13 55 14" src="https://github.com/tauri-apps/tauri/assets/109857267/9026837a-b20f-45b8-9284-909226245bc3">
It uses `/Users/runner/work/MDog/MDog/src-tauri/target/release/app` path, but should use `/Users/runner/work/MDog/MDog/src-tauri/target/aarch64-apple-darwin/release/app`, I'm using `tree` command to figure out this:
```bash
│   ├── target
│   │   ├── CACHEDIR.TAG
│   │   ├── aarch64-apple-darwin
│   │   │   ├── CACHEDIR.TAG
│   │   │   └── release
│   │   │       ├── app
```
Please advise how can I fix this?
