### DISCUSSION TITLE
Can the names of these features be used as suffixes for the bundle when enabling certain features?

### DISCUSSION THREAD

**Discussion by thep0y** [tauri-apps/tauri#8356] [Q&A]
```toml
[package]
name = "app"

# ...

[features]
compress = ["dep:image"]
```

```bash
tauri build --features compress # bundle name: app-compress.app, app_0.1.0_aarch64-compress.dmg
tauri build # bundle name: app.app, app_0.1.0_aarch64.dmg
```
