### DISCUSSION TITLE
Webkit is totally unstable, so we need to use chromium or firefox instead

### DISCUSSION THREAD

**Discussion by maurerdietmar** [tauri-apps/tauri#8524] [General]
I am unable to run any serious wasm application with webkit on Linux:

https://github.com/tauri-apps/tauri/issues/7154

It also seems that the webkit project does not fix those bugs in reasonable time:

https://bugs.webkit.org/show_bug.cgi?id=259441

So how can I use tauri to make a cross platform app? Any plans to support firefox or chromium?

**Comment by FabianLars** [comment]
We can't support firefox since there's no firefox based webview library.

Chromium via CEF is still not off the table but there's no ETA for that. So if you need _good_ linux support now/soon i can't 100% recommend tauri (for Linux) as of now. (I used to be more "forgiving" but with webkitgtk getting worse/more unstable each release i changed my mind)

Side note, we're also working on a servo webview together with igalia. But servo of course won't be able to compete with the normal browsers feature wise anytime soon, if ever.

**Reply by Ramblurr** [reply]
> So if you need _good_ linux support now/soon i can't 100% recommend tauri (for Linux) as of now.

Checking in a bit over a year later now, has the story changed at all? Can we use Tauri if we need excellent Linux support?

**Reply by FabianLars** [reply]
No

Edit: work on gtk4 (to slightly improve the webkitgtk situation) and cef has begun recently.

**Reply by FeldrinH** [reply]
Some relevant issues to track: https://github.com/tauri-apps/wry/issues/1064, https://github.com/chromiumembedded/cef/issues/3836.

**Reply by pomykalakyle** [reply]
Checking in on this - is Tauri on Linux still a problem? I really want to use it over electron but I need it to work on Linux good

**Reply by metkm** [reply]
@pomykalakyle I would look for something else then. Webview on linux is still shit. It's a linux problem. Also, basic stuff like loading a video is not working.

**Reply by thiagovianav** [reply]
> Checking in on this - is Tauri on Linux still a problem? I really want to use it over electron but I need it to work on Linux good

@pomykalakyle 
You can actually already use the CEF branch, but its very experimental.

I had great success using it on a fresh new project but tbh I'm a bit stuck in some older projects that i wanted to get out of Webkit.

this is the code to put at Cargo.toml:

```toml
[target."cfg(target_os = \"linux\")".dependencies.tauri]
version = "2"
features = ["cef"]
default-features = false

[target."cfg(not(target_os = \"linux\"))".dependencies.tauri]
version = "2"
features = []

[patch.crates-io.tauri]
git = "https://github.com/tauri-apps/tauri"
branch = "feat/cef"
```
