### DISCUSSION TITLE
iOS focused input with keyboard causes entire screen to scroll.

### DISCUSSION THREAD

**Discussion by lpmsh** [tauri-apps/tauri#9368] [Q&A]
I'm having an issue with the tauri beta that I can't seem to find a fix for. From the most basic tauri beta react app (created with `npm create tauri-app@latest -- --beta`) when an input is focused and the iOS keyboard is active, the entrie webview will scroll out of the way. 

### When the input is not focused (hidden keyboard) the app looks as expected.

<img src="https://github.com/tauri-apps/tauri/assets/99554127/fecb4eb6-3f71-410e-93b9-c00d752070bb" alt="drawing" width="300"/>

### Then, when the input is focused and the keyboard pops up, the whole app scrolls (seemingly making the bottom of the app meet the keyboard). 

<img src="https://github.com/tauri-apps/tauri/assets/99554127/cf789e85-32d6-40ba-80a2-2cb6e45d169a" alt="drawing" width="300"/>

It would be understandable for the view to move a bit because the input is probably in the way of the keyboard but the amount it does move is strange. And not being able to control this scroll isn't optimal.

So far, I've looked at https://github.com/tauri-apps/wry/issues/557 but I'm not sure that is a related issue. I've tried various css configurations with height and tried to fix it with JS by monitoring inner height and adjusting the screen accordingly but nothing has seemed to work so far. 

Heres `App.tsx`
```tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import { invoke } from "@tauri-apps/api/core";
import "./App.css";

function App() {
  const [greetMsg, setGreetMsg] = useState("");
  const [name, setName] = useState("");

  async function greet() {
    // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
    setGreetMsg(await invoke("greet", { name }));
  }

  return (
    <div className="container">
      <h1>Welcome to Tauri!</h1>

      <div className="row">
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>

      <p>Click on the Tauri, Vite, and React logos to learn more.</p>

      <form
        className="row"
        onSubmit={(e) => {
          e.preventDefault();
          greet();
        }}
      >
        <input
          id="greet-input"
          onChange={(e) => setName(e.currentTarget.value)}
          placeholder="Enter a name..."
        />
        <button type="submit">Greet</button>
      </form>

      <p>{greetMsg}</p>
    </div>
  );
}

export default App;

```

And `styles.css`

```css
:root {
  font-family: Inter, Avenir, Helvetica, Arial, sans-serif;
  font-size: 16px;
  line-height: 24px;
  font-weight: 400;

  color: #0f0f0f;
  background-color: #f6f6f6;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-text-size-adjust: 100%;
}

.container {
  margin: 0;
  padding-top: 10vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
}

.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: 0.75s;
}

.logo.tauri:hover {
  filter: drop-shadow(0 0 2em #24c8db);
}

.row {
  display: flex;
  justify-content: center;
}

a {
  font-weight: 500;
  color: #646cff;
  text-decoration: inherit;
}

a:hover {
  color: #535bf2;
}

h1 {
  text-align: center;
}

input,
button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  color: #0f0f0f;
  background-color: #ffffff;
  transition: border-color 0.25s;
  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
}

button {
  cursor: pointer;
}

button:hover {
  border-color: #396cd8;
}
button:active {
  border-color: #396cd8;
  background-color: #e8e8e8;
}

input,
button {
  outline: none;
}

#greet-input {
  margin-right: 5px;
}

@media (prefers-color-scheme: dark) {
  :root {
    color: #f6f6f6;
    background-color: #2f2f2f;
  }

  a:hover {
    color: #24c8db;
  }

  input,
  button {
    color: #ffffff;
    background-color: #0f0f0f98;
  }
  button:active {
    background-color: #0f0f0f69;
  }
}

```

Any suggestions would be great. Thanks.
