### DISCUSSION TITLE
TargetKind::LogDir not working (tauri_plugin_log) (tauri v2)

### DISCUSSION THREAD

**Discussion by arashi-dev** [tauri-apps/tauri#9532] [Q&A] [answered]
I am trying to use `tauri_plugin_log`.
Everything works as expected. It does log on `TargetKind::Stdout` and `TargetKind::Webview` BUT it doesn't log in `TargetKind::LogDir { ... }`

Here is my config in `lib.rs`:
```rs
tauri_plugin_log::Builder::new()
    .targets([
        Target::new(TargetKind::LogDir {
            file_name: Some("main".into()),
        }),
        Target::new(TargetKind::Stdout),
        Target::new(TargetKind::Webview),
    ])
    .with_colors(ColoredLevelConfig::default())
    .max_file_size(2 * 1024 /* 2MB */)
    .level(LevelFilter::Info)
    .rotation_strategy(RotationStrategy::KeepAll)
    .build()
```

###### Cargo.toml
```toml
[dependencies]
tauri = { version = "2.0.0-beta", features = ["..."] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2", features = [
    "colored",
] }
# ...
```

The `log:default` capability is already set correctly.
