### ISSUE TITLE
release asset naming inconsistencies

### ISSUE THREAD

**Issue by jebarpg** [tauri-apps/tauri#10465]
My {app_name} currently is 'deploy' my files/assets that are attached to the release look like the following:

```bash
deploy-1.0.1-1.x86_64.rpm

deploy_1.0.1_aarch64.dmg

deploy_1.0.1_amd64.AppImage

deploy_1.0.1_amd64.deb

deploy_1.0.1_x64-setup.exe

deploy_1.0.1_x64.dmg

deploy_1.0.1_x64_en-US.msi

deploy_aarch64.app.tar.gz

deploy_x64.app.tar.gz

Source code
(zip)

Source code
(tar.gz)
```

The first inconsistency issues I have is with the assets `deploy-1.0.1-1.x86_64.rpm` , `deploy_1.0.1_x64-setup.exe`, and `deploy_1.0.1_x64_en-US.msi` which have '-' as separators instead of '_' like the rest.

The second inconsistency issue I have is with the last two assets `deploy_aarch64.app.tar.gz` and `deploy_x64.app.tar.gz` which do not have the version number in the naming. They should look like this instead: `deploy_1.0.1_aarch64.app.tar.gz` and `deploy_1.0.1_x64.app.tar.gz`

I am not sure if the last two files aren't getting the version added because of the 
```yaml
with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
```
in the action or if there is something else internal that is going on with the action.
If there is something that I can change with the action let me know or if this is something internal with your action then I would like to request these to be changed for consistent naming conventions across all assets generated using this release action.

Here is my workflow yml file to help debug this issue.

```yaml
name: '🚀 Publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    # increase this 15 minutes to something longer if your project starts taking longer to build. 
    # This is just an inital fail safe so your build doesn't use up to 6 hours of time on your 2,000/month billable actions minutes.
    timeout-minutes: 15 # Set a reasonable timeout, shorter than GitHub's default 6 hours
    steps:
      - uses: actions/checkout@v4

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: 🛠️ Set up Bun.sh
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 🔧 Install 🦀 Rust 🟢✨ Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: 🔧 Install 📦 Dependencies (🐧Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: 🔧 Install 💻 Frontend 📦 Dependencies
        # change this to npm, pnpm or bun depending on which one you use.  
        run: bun install --frozen-lockfile # current equivalent of 'npm ci' for bun (as of 07/29/2024 see/subscribe to this issue: https://github.com/oven-sh/bun/issues/5283 for updates).
        # Info: For reproducible installs, use --frozen-lockfile . This will install the exact versions of each package specified in the lockfile. 
        
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'v__VERSION__'
          #releaseBody: '👀 See the 📂 assets to ⬇️ download this 🆕 version and 🔧 install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

```
