### ISSUE TITLE
[bug] Rust build profile with `lto=true` makes iOS build fail

### ISSUE THREAD

**Issue by IT-ess** [tauri-apps/tauri#10553]
### Describe the bug

The `pnpm tauri ios build` command fails when the `lto` (link time optimizations) is set to true in Cargo.toml

### Reproduction

1. Create a new project with the `create-tauri` CLI
2. Add iOS target with `pnpm tauri ios init` and set a different build name in `tauri.conf.json`
3. Paste these build profiles as suggested in [this page](https://v2.tauri.app/concept/size/)
```toml
[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
```
4. Try to build the app with `pnpm tauri ios build`
5. The command exits with code 1
```
[tauri_cli_node] Library from /Users/Alexis.Loiseau1/Documents/Repos/Perso/testrc/src-tauri/target/aarch64-apple-ios/release/libtestrc_lib.a does not include required runtime symbols. This means you are likely missing the tauri::mobile_entry_point macro usage, see the documentation for more information: https://v2.tauri.app/start/migrate/from-tauri-1
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

Either complete the docs and the CLI output to precise that LTO aren't supported on iOS, or fix the issue.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.6.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.14.0
    - pnpm: 9.7.0
    - yarn: 1.22.22
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite

[-] iOS
    - Developer Teams: Whiteroom SARL (ID: XXX)
```

### Stack trace

```text
Error [tauri_cli_node] Library from /Users/Alexis.Loiseau1/Documents/Repos/Perso/testrc/src-tauri/target/aarch64-apple-ios/release/libtestrc_lib.a does not include required runtime symbols. This means you are likely missing the tauri::mobile_entry_point macro usage, see the documentation for more information: https://v2.tauri.app/start/migrate/from-tauri-1
 ELIFECYCLE  Command failed with exit code 1.
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Build\ Rust\ Code /Users/Alexis.Loiseau1/Library/Developer/Xcode/DerivedData/testrc-dzmuatoxkfasbcgouarbyjseuqcd/Build/Intermediates.noindex/testrc.build/release-iphoneos/testrc_iOS.build/Script-5F86A48A781CEDF3943154C7.sh (in target 'testrc_iOS' from project 'testrc')
(1 failure)
    Error command ["xcodebuild"] exited with code 65
 ELIFECYCLE  Command failed with exit code 1.
```
