### ISSUE TITLE
[bug] Flatpak error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found

### ISSUE THREAD

**Issue by nekename** [tauri-apps/tauri#11210]
### Describe the bug

I am trying to create a Flatpak of my application as described at https://tauri.app/distribute/flatpak/.

I have created the manifest, a local repository, built the app into my local repo, and installed the app from my local repo.

When I try to run the app, it fails to link against glibc 2.39, which is presumably available in the version of Debian/Ubuntu that the .deb targets but not my openSUSE Tumbleweed system.

```
➜ flatpak run me.amankhanna.opendeck
opendeck: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by opendeck)
```

Manifest
```yaml
id: me.amankhanna.opendeck

runtime: org.gnome.Platform
runtime-version: "46"
sdk: org.gnome.Sdk

command: opendeck
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=all
  - --share=ipc
  - --share=network

modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: file:///home/aman/Documents/OpenDeck-flatpak/release.deb
        sha256: b6938d768b47abebc3f810a6087f81f0352a83ffc3ceaba36fcdcec28d800a8b
        only-arches: [ x86_64 ]
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/opendeck /app/bin/opendeck
      - install -Dm644 usr/share/applications/opendeck.desktop /app/share/applications/me.amankhanna.opendeck.desktop
      - install -Dm644 usr/share/icons/hicolor/512x512/apps/opendeck.png /app/share/icons/hicolor/512x512/apps/me.amankhanna.opendeck.png
      # - install -Dm644 me.amankhanna.opendeck.metainfo.xml /app/share/metainfo/me.amankhanna.opendeck.rosary.metainfo.xml
```

### Full `tauri info` output

```text
➜ cargo tauri info
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: openSUSE 20241001.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.4
    ✔ rsvg2: 2.59.1
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.16.0
    - npm: 10.8.1

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.2
    - tauri-cli 🦀: 2.0.1
    - @tauri-apps/api : 2.0.1
    - @tauri-apps/cli : 2.0.1

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : not installed!
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : not installed!
    - tauri-plugin-autostart 🦀: 2.0.1
    - @tauri-apps/plugin-autostart : not installed!
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : not installed!

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: http://localhost:57118 https://ninjadev64.github.io https://plugins.amankhanna.me; frame-src http://localhost:57118; connect-src ipc: http://ipc.localhost https://ninjadev64.github.io https://api.github.com https://plugins.amankhanna.me;
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```
