### ISSUE TITLE
[bug] (Maybe Not) Tauri cannot handle resources imported with <link>.

### ISSUE THREAD

**Issue by origin-coding** [tauri-apps/tauri#11276]
### Describe the bug

My Tauri app only displays blank screen after building for production, and some requests returns "No data found for resource with given identifier":
![image](https://github.com/user-attachments/assets/a64dfbf9-3218-4ef7-8da1-43d5f07e3b12)
![image](https://github.com/user-attachments/assets/0f5e44dd-4e2d-4b06-b3fc-b707d5610729)

### Reproduction

I'm using Nuxt + Vite as my frontend framework, and I found that the screen is blank after building for production. Then I turned on "devtools" feature in my Cargo.toml, and tried to debug in production. I found that some files cannot be correctly loaded, like the image below:
![image](https://github.com/user-attachments/assets/54e15e75-883e-491b-b551-175fd3ff933f)

And I found all files requested by `index.html` and with <link> tag not correctly returned, the status code was 200 OK, but no data was returned.
![image](https://github.com/user-attachments/assets/d3fa4970-adda-4cf7-aacb-2509617e8c26)
So I tried to change one <link> tag with <script> tag, and it can be correctly returned, like this: 
![image](https://github.com/user-attachments/assets/c9b818ea-3f95-4fd3-a622-f24ee999848a)
and the difference looks like this: 
![image](https://github.com/user-attachments/assets/f2c62032-60db-4dc2-9784-0a8f2b350ef2)

### Expected behavior

Tauri can correctly handle these files and displays the original page like dev.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - yarn: 1.22.19
    - npm: 10.4.0

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.0-rc.0
    - @tauri-apps/cli : 2.0.0-rc.18

[-] Plugins
    - tauri-plugin-store 🦀: 2.0.1
    - @tauri-apps/plugin-store : 2.0.0
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : 2.0.0
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : 2.0.0
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../.output/public
    - devUrl: http://localhost:3000/
    - framework: Vue.js (Nuxt)
    - bundler: Vite
Done in 26.85s.
```

**Comment by origin-coding** [comment]
My tauri.conf.json file: 
```json
{
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn generate",
    "frontendDist": "../.output/public",
    "devUrl": "http://localhost:3000"
  },
  "bundle": {
    "active": true,
    "category": "DeveloperTool",
    "copyright": "",
    "targets": "all",
    "externalBin": [],
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ],
    "windows": {
      "certificateThumbprint": null,
      "digestAlgorithm": "sha256",
      "timestampUrl": ""
    },
    "longDescription": "",
    "macOS": {
      "entitlements": null,
      "exceptionDomain": "",
      "frameworks": [],
      "providerShortName": null,
      "signingIdentity": null
    },
    "resources": [],
    "shortDescription": "",
    "linux": {
      "deb": {
        "depends": []
      }
    }
  },
  "productName": "Alacrity",
  "mainBinaryName": "Alacrity",
  "version": "../package.json",
  "identifier": "Alacrity",
  "plugins": {},
  "app": {
    "withGlobalTauri": false,
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "Alacrity",
        "width": 800,
        "maximized": true
      }
    ],
    "security": {
      "csp": null
    }
  }
}
```

My Cargo.toml file: 
```toml
[package]
name = "alacrity"
version = "0.0.0"
description = "A toolbox app built with Truri and Vue."
authors = ["origin-coding"]
license = "GPL-3"
repository = "https://github.com/origin-coding/alacrity"
edition = "2021"


[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-rc", features = ["devtools"] }
# Tauri plugins
tauri-plugin-single-instance = { version = "2.0.0-rc" }
tauri-plugin-store = "2.0.0-rc"
tauri-plugin-shell = "2.0.0-rc"
tauri-plugin-dialog = "2.0.0-rc"
tauri-plugin-clipboard-manager = "2.0.1"
tauri-plugin-fs = "2.0.0-rc"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is a URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

```

My nuxt.config.ts file: 
```ts
// noinspection JSUnusedGlobalSymbols

export default defineNuxtConfig({
  ssr: false,
  devtools: {
    enabled: true,

    timeline: {
      enabled: true,
    },
  },
  css: ["~/assets/index.less"],
  modules: [
    "@nuxt/eslint",
    "@unocss/nuxt",
    "@tdesign-vue-next/nuxt",
    "@vueuse/nuxt",
    "@nuxtjs/i18n",
    "@pinia/nuxt",
    "@nuxt/image",
    "@nuxt/content",
    "@nuxtjs/color-mode",
  ],
  tdesign: {
    resolveIcons: true,
    esm: true,
  },
  i18n: {
    vueI18n: "./i18n.config.ts",
  },
  // Safari 13(Webview used in Linux and macOS by Tauri) does not support top-level await.
  // We need to manually configure it.
  vite: {
    esbuild: {
      supported: {
        "top-level-await": true,
      },
    },
    build: {
      modulePreload: false
    },
  },
  experimental: {
    // To use Node's API, such as Buffer, etc.
    clientNodeCompat: true,
  },
  content: {
    highlight: {
      theme: {
        light: "light-plus",
        dark: "dark-plus",
        default: "dark-plus",
      },
    },
    respectPathCase: true,
    experimental: {
      clientDB: true, // If not set, contents are Not Found after generating static files.
    },
  },
  // Nuxt content's code highlight works only when <html> has a class called light/dark, without any suffix.
  colorMode: {
    classSuffix: "",
  },
});

```
