### ISSUE TITLE
[bug] Disable close, move, resize, maximize and minimize functions for parent of file dialog on Linux.

### ISSUE THREAD

**Issue by odeyal0** [tauri-apps/tauri#11319]
### Describe the bug

Close, move, resize, maximize and minimize functions for parent of dialog is not disabled on Linux.

dialog code:
```rust
#[tauri::command]
async fn download_files(
    urls: Vec<String>,
    default_directory: bool,
    app_handle: tauri::AppHandle,
    window: tauri::WebviewWindow,
) -> Result<String, String> {
    ...
    let dialog_result = match app_handle
    .dialog()
    .file()
    .set_parent(&window)
    .blocking_pick_folder()
    {
        Some(val) => val,
        None => return Err("Dialog was closed".to_string()),
    };

    dialog_result.into_path().unwrap()
    ...
}
```

Cargo.toml
```toml
...
[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
once_cell = "1.19.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [ "devtools", "webview-data-url"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
tauri-plugin-cli = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2.0.1"
tauri-plugin-window-state = { version = "2.0.0" }
tauri-plugin-fs = { version = "2.0.0", features = ["watch"] }
tauri-plugin-single-instance = { version = "2.0.0" }
tauri-plugin-process = "2.0.0"
dunce = "1.0.4"
base64 = "0.21.7"
anyhow = "1.0.86"
open = "5.3.0"
content_disposition = "0.4.0"
urlencoding = "2.1.3"
[target.'cfg(not(windows))'.dependencies]
openssl-sys = { version = "=0.9.72", features = ["vendored"] }
openssl = { version = "=0.10.38" }
...
```

### Full `tauri info` output

```text
Dev machine tauri info

[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.19.0
    - pnpm: 9.5.0
    - npm: 10.2.3

[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.1 (outdated, latest: 2.0.2)

[-] Plugins
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-cli 🦀: 2.0.1
    - @tauri-apps/plugin-cli : not installed!
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : not installed!
    - tauri-plugin-window-state 🦀: 2.0.1
    - @tauri-apps/plugin-window-state : not installed!
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : not installed!
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../web/dist
    - devUrl: http://localhost:3000/
```
