### ISSUE TITLE
[bug] Unable to reposition the window in Windows 11 when window decorations are set to false (Repositioning is affected, not RESIZING)

### ISSUE THREAD

**Issue by ninetynin** [tauri-apps/tauri#11345]
### Describe the bug

I found [issue1](https://github.com/tauri-apps/tauri/issues/8519) [issue2](https://github.com/tauri-apps/tauri/issues/10735) but both are fixes for resizing the window when using custom titlebar by setting the decorations to false but I'm unable to move reposition the window to some other (x,y) position with same size in windows11

https://github.com/user-attachments/assets/1fbdb65f-c330-4a97-a472-5ccd7c10e201

As you can see in the video I'm not able to move the window to some other location 

### Reproduction

set `"decorations": false` in tauri.conf.json and select vanilla js while creating the app and these are frontend codes

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div data-tauri-drag-region class="titlebar" id="titlebar">
        <div>
            <div class="titlebar-button" id="titlebar-minimize">
                <img src="https://api.iconify.design/mdi:window-minimize.svg" alt="minimize" />
            </div>
            <div class="titlebar-button" id="titlebar-maximize">
                <img src="https://api.iconify.design/mdi:window-maximize.svg" alt="maximize" />
            </div>
            <div class="titlebar-button" id="titlebar-close">
                <img src="https://api.iconify.design/mdi:close.svg" alt="close" />
            </div>
        </div>
    </div>
    <script src="main.js"></script>
</body>
</html>
```
styles.css
```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body {
  height: 100%;
  overflow: hidden;
  padding: 5px; 
}

.titlebar {
  height: 30px;
  background: #ffffff;
  user-select: none;
  display: flex;
  justify-content: space-between;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 10;
  transition: opacity 0.3s;
}

.titlebar-button {
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 30px;
  height: 30px;
  cursor: pointer;
}

.titlebar-button:hover {
  background: #c35b8f;
}
```

main.js
```
const { appWindow } = window.__TAURI__.window;
const { invoke } = window.__TAURI__;

document
    .getElementById('titlebar-minimize')
    .addEventListener('click', () => appWindow.minimize());
document
    .getElementById('titlebar-maximize')
    .addEventListener('click', () => appWindow.toggleMaximize());
document
    .getElementById('titlebar-close')
    .addEventListener('click', () => appWindow.close());
```

### Full `tauri info` output

```text
PS S:\testingprojects\rust\browesertestver6> npm run tauri info

> browesertestver6@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.83.0-nightly (6b9676b45 2024-10-12)
    ✔ cargo: 1.83.0-nightly (15fbd2f60 2024-10-08)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.16.0
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.0
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 1.6.2
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```
