### ISSUE TITLE
[bug] On using async block on for state then on starting the tauri app it start closing and opening automatically in loop

### ISSUE THREAD

**Issue by avinash-kumar-prajapati-AI** [tauri-apps/tauri#11895]
### Describe the bug

```rs
// src/lib.rs
mod db;

// use tauri::{command, State};
use tauri::Manager;
use sqlx::{sqlite::SqlitePool};
use std::error::Error;

use db::*;
use std::sync::Arc;


struct AppState {
    pool: Arc<SqlitePool>,
}


#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
    .setup(|app| {
        // Use an async runtime to initialize the database
        let async_setup = async {
            match initialize_db().await {
                Ok(pool) => {
                    // Wrap the pool in Arc and store it in the app state
                    app.manage(AppState {
                        pool: Arc::new(pool),
                    });
                    Ok::<(), Box<dyn Error>>(()) // Return Result with Box<dyn Error>
                }
                Err(e) => {
                    // Log the error and return a Box<dyn Error>
                    eprintln!("Database initialization failed: {:?}", e);
                    // Only box the error once as Box<dyn Error>
                    Err(Box::new(e) as Box<dyn Error>) // Box the error correctly
                }
            }
        };

        // Run the async setup
        tauri::async_runtime::block_on(async_setup)
    })
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            // add_note_item
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
``` 

**and in db.rs**

```rs
use sqlx::{sqlite::{SqlitePool}, Sqlite};
use std::error::Error;
use sqlx::migrate::MigrateDatabase;


pub async fn initialize_db() -> Result<SqlitePool, sqlx::Error> {
    // Define the SQLite database URL (for example, an in-memory DB for testing or a file-based DB)
    // some code.....
   
    // Create the connection pool to the SQLite database
    let pool = SqlitePool::connect(db_url).await?;
    
    // Create the schema for the notes table if it doesn't already exist

    Ok(pool)
}
```

Please let me know the way o if there is any solution for this, i am using following dependencies : 
```toml
[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tokio = { version = "1.42.0", features = ["full"] }

async-std = "1.13.0"
chrono = { version = "0.4.38", features = ["serde"] }
futures = "0.3.31"
sqlx = { version = "0.8.2", features = ["runtime-async-std", "tls-native-tls", "sqlite", "chrono"] }
```

### Full `tauri info` output

```text
No any error output as the app start successfully but it get stuck in loop of automatically closing and opening
```
