### ISSUE TITLE
[bug] `@tauri-apps/cli` NPM package contains unnecessary files

### ISSUE THREAD

**Issue by Sitin** [tauri-apps/tauri#12139]
### Describe the bug

The following path in `packages/cli/Cargo.toml` is incorrect in [NPM package](https://www.npmjs.com/package/@tauri-apps/cli?activeTab=code):

```toml
[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.16", default-features = false, features = ["napi4"] }
napi-derive = "2.16"
tauri-cli = { path = "../../crates/tauri-cli", default-features = false }  # INCORRECT PATH
log = "0.4.21"
```

### Reproduction

Install `@tauri-apps/cli` NPM package and check `Cargo.toml` file.

### Expected behavior

The path should be either correct or file should be excluded from the package.

### Full `tauri info` output

```text
Irrelevant
```
