### ISSUE TITLE
[bug] Installer works when built locally, not when built via GH actions

### ISSUE THREAD

**Issue by Joaquin121121** [tauri-apps/tauri#12596]
### Describe the bug

The GH actions are executed successfully and all the required files for it to run are available, but for some reason, the app installed via the .msi provided by the GH release just doesnt show anything.  The .msi built via running npm run tauri build in my local environment does work as expected, installing a working version of the app. Both the apps installed by the .msi provided by the GH release and by the locally built .msi are of the same size.

### Reproduction

https://github.com/Joaquin121121/ErgoAppDesktop
release.yml:
```yml
name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend and verify directories
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents before build:"
          ls -la
          npm run build
          echo "Directory contents after build:"
          ls -la
          echo "Dist directory contents:"
          ls -la dist
          echo "Checking src-tauri directory:"
          ls -la src-tauri
        shell: bash

      - name: Enable debug logging
        run: |
          echo "RUST_LOG=debug" >> $GITHUB_ENV
          echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        shell: bash

      - name: Install Tauri dependencies (macOS only)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          brew install create-dmg
      - name: Install Tauri dependencies (Windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUST_LOG: debug
          RUST_BACKTRACE: 1
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "ErgoApp Desktop v${{ github.ref_name }}"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false

      - name: Check build artifacts
        run: |
          echo "Checking src-tauri/target directory:"
          ls -la src-tauri/target || true
          echo "Checking release artifacts:"
          ls -la src-tauri/target/release || true
        shell: bash
```
logs are available in the action workflow run history, I went through different versions with different logs to try and debug the problem but I have been unable to do so. 

### Expected behavior

For the workflow to produce a working version of the .msi, one that produces a working version of the app

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 132.0.2957.127
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.84.0 (9fc6b4312 2025-01-07)
    ✔ cargo: 1.84.0 (66221abde 2024-11-19)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.2
    - npm: 10.5.0

[-] Packages
    - tauri 🦀: 2.2.5
    - wry 🦀: 0.48.1
    - tauri-cli 🦀: 2.2.5
    - @tauri-apps/api : 2.2.0

[-] Plugins
    - tauri-plugin-log 🦀: 2.2.1
    - @tauri-apps/plugin-log : not installed!
    - tauri-plugin-updater 🦀: 2.4.0
    - @tauri-apps/plugin-updater : 2.4.0
    - tauri-plugin-process 🦀: 2.2.0
    - @tauri-apps/plugin-process : 2.2.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text

```
