### ISSUE TITLE
[bug] Experiencing issues with the embedded files after build.

### ISSUE THREAD

**Issue by mkhantamir** [tauri-apps/tauri#12795]
### Describe the bug

My project uses Next.js for the frontend. I'm trying to serve a second Next.js project as a sidecar on port 2803 (via Axum in src-tauri/src/init.ts).

I added \"resources\": [\"static/**/*\"] to tauri.conf.json, and development mode works fine but the after build it doesn't work.

The "static" folder is inside 'src-tauri'

### Reproduction

```rs
pub async fn serve_second() {
    let app = Router::new()
        .route("/health", get(check_health))
        .fallback_service(ServeDir::new("static/")
            .fallback(ServeFile::new("static/index.html"))
        );

    let listener = tokio::net::TcpListener::bind("127.0.0.1:2803").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
async fn check_health() -> String {
    "Hello from axum.".to_string()
}
```
```json
"bundle": {
    ...
    "resources": ["static/**/*"]
  }
```
### Expected behavior

"http://localhost:2803" should display the second Next.js web, but it's returning a 404 error. The '/health' endpoint is working correctly

### Full `tauri info` output

```text
○  (Static)  prerendered as static content

   Compiling app v0.1.0 (C:\Users\Local Streaming\Desktop\arcanis\packages\client\src-tauri)
    Finished `release` profile [optimized] target(s) in 1m 02s
    Built application at: C:\Users\Local Streaming\Desktop\arcanis\packages\client\src-tauri\target\release\app.exe
    Info Target: x64
    Running candle for "main.wxs"
    Running light to produce C:\Users\Local Streaming\Desktop\arcanis\packages\client\src-tauri\target\release\bundle\msi\Mesa Broadcast_0.1.0_x64_en-US.msi
    Info Target: x64
    Running makensis.exe to produce C:\Users\Local Streaming\Desktop\arcanis\packages\client\src-tauri\target\release\bundle\nsis\Mesa Broadcast_0.1.0_x64-setup.exe
    Finished 2 bundles at:
        C:\Users\Local Streaming\Desktop\arcanis\packages\client\src-tauri\target\release\bundle\msi\Mesa Broadcast_0.1.0_x64_en-US.msi
        C:\Users\Local Streaming\Desktop\arcanis\packages\client\src-tauri\target\release\bundle\nsis\Mesa Broadcast_0.1.0_x64-setup.exe
```

### Stack trace

```toml
[dependencies]
log = "0.4"
tauri = { version = "2.2.4", features = ["tray-icon"] }
tauri-plugin-log = "2.0.0-rc"
tauri-plugin-process = "2.2.0"
axum = "0.8.1"
socketioxide = "0.16.1"
tokio = { version = "1.43.0", features = ["full"] }
regex = "1.11.1"
http = "1.2.0"
tower-http = { version = "0.6.2", features = ["cors", "fs", "util"] }
tauri-plugin-fs = "2.2.0"
serde_json = "1.0.138"
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
```
