### ISSUE TITLE
How to get rid of the black border when disabling window decorations?

### ISSUE THREAD

**Issue by 34205037** [tauri-apps/tauri#13176]
How to disable the black window border?

![Image](https://github.com/user-attachments/assets/1f5a598d-566e-4bc6-89bc-e0c93b032a69)

tauri.conf.json
```json
"windows": [
      {
        "width": 800,
        "height": 600,
        "decorations": false,
        "shadow": true,
        "transparent": true,
        "center": true
      }
    ]
```

```css
html, body, div {
        padding: 0;
        margin: 0;
        height: 100%;
      }

      body {
        background-color: transparent;
      }
```

Windows 10 22H2 19045.5608 / Tauri 2.4.0
