### ISSUE TITLE
[bug] Cannot build on Windows after updating crate

### ISSUE THREAD

**Issue by CalvinWilkinson** [tauri-apps/tauri#13283]
### Describe the bug

After updating all of the crates to the latest version, I am getting build issues.

When running the build, I am getting the following error in my terminal:
```bash
   Compiling tauri-codegen v2.2.0
error[E0308]: mismatched types
   --> C:\Users\kinso\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-plugin-2.0.4\src\build\mod.rs:140:58
    |
140 |       tauri_utils::plugin::define_global_api_script_path(path);
    |       -------------------------------------------------- ^^^^ expected `&Path`, found `PathBuf`
    |       |
    |       arguments to this function are incorrect
    |
note: function defined here
   --> C:\Users\kinso\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-utils-2.4.0\src\plugin.rs:22:10
    |
22  |   pub fn define_global_api_script_path(path: &Path) {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider borrowing here
    |
140 |       tauri_utils::plugin::define_global_api_script_path(&path);
    |                                                          +

   Compiling hyper-rustls v0.27.5
For more information about this error, try `rustc --explain E0308`.
error: could not compile `tauri-plugin` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
 ELIFECYCLE  Command failed with exit code 101.
```

### Reproduction

1. Check out dependabot PR branch
2. Run build using the `cargo build --manifest-path \"./src-tauri/Cargo.toml\"`
3. Observed the error stated above

### Expected behavior

I expected the build to pass with no issues or errors.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 135.0.3179.85
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.86.0 (05f9846f8 2025-03-31)
    ✔ cargo: 1.86.0 (adf9b6ad1 2025-02-28)
    ✔ rustup: 1.28.1 (f9edccde0 2025-03-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.13.0
    - pnpm: 10.9.0
    - npm: 10.9.2
    - deno: deno 2.2.11

[-] Packages
    - tauri 🦀: 2.5.1
    - tauri-build 🦀: 2.2.0
    - wry 🦀: 0.51.2
    - tao 🦀: 0.33.0
    - @tauri-apps/api : 2.5.0
    - @tauri-apps/cli : 2.2.5 (outdated, latest: 2.5.0)

[-] Plugins
    - tauri-plugin-process 🦀: 2.2.1
    - @tauri-apps/plugin-process : 2.2.0 (outdated, latest: 2.2.1)
    - tauri-plugin-window-state 🦀: 2.2.2
    - @tauri-apps/plugin-window-state : 2.2.1 (outdated, latest: 2.2.2)
    - tauri-plugin-updater 🦀: 2.7.1
    - @tauri-apps/plugin-updater : 2.0.0 (outdated, latest: 2.7.1)
    - tauri-plugin-shell 🦀: 2.2.1
    - @tauri-apps/plugin-shell : 2.2.1
    - tauri-plugin-store 🦀: 2.2.0
    - @tauri-apps/plugin-store : 2.2.0
    - tauri-plugin-fs 🦀: 2.2.1
    - @tauri-apps/plugin-fs : 2.2.0 (outdated, latest: 2.2.1)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3500/
    - framework: React (Next.js)
    - bundler: Vite
```

### Stack trace

```text
> cargo build --manifest-path "./src-tauri/Cargo.toml"

   Compiling proc-macro2 v1.0.93
   Compiling unicode-ident v1.0.14
   Compiling cfg-if v1.0.0
   Compiling windows_x86_64_msvc v0.52.6
   Compiling autocfg v1.4.0
   Compiling byteorder v1.5.0
   Compiling serde v1.0.219
   Compiling stable_deref_trait v1.2.0
   Compiling siphasher v0.3.11
   Compiling itoa v1.0.14
   Compiling once_cell v1.20.2
   Compiling getrandom v0.1.16
   Compiling syn v1.0.109
   Compiling fnv v1.0.7
   Compiling litemap v0.7.4
   Compiling writeable v0.5.5
   Compiling memchr v2.7.4
   Compiling icu_locid_transform_data v1.5.0
   Compiling icu_properties_data v1.5.0
   Compiling parking_lot_core v0.9.10
   Compiling utf8_iter v1.0.4
   Compiling write16 v1.0.0
   Compiling getrandom v0.2.15
   Compiling phf_shared v0.10.0
   Compiling icu_normalizer_data v1.5.0
   Compiling utf16_iter v1.0.5
   Compiling phf_shared v0.8.0
   Compiling log v0.4.25
   Compiling scopeguard v1.2.0
   Compiling bytes v1.9.0
   Compiling rand_core v0.6.4
   Compiling ryu v1.0.18
   Compiling smallvec v1.13.2
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling new_debug_unreachable v1.0.6
   Compiling thiserror v2.0.11
   Compiling precomputed-hash v0.1.1
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.15.2
   Compiling mac v0.1.1
   Compiling bitflags v1.3.2
   Compiling lock_api v0.4.12
   Compiling utf-8 v0.7.6
   Compiling futf v0.1.5
   Compiling semver v1.0.24
   Compiling dtoa v1.0.9
   Compiling winnow v0.6.24
   Compiling phf v0.10.1
   Compiling strsim v0.11.1
   Compiling ident_case v1.0.1
   Compiling typeid v1.0.2
   Compiling http v1.2.0
   Compiling dtoa-short v0.3.5
   Compiling tendril v0.4.3
   Compiling matches v0.1.10
   Compiling itoa v0.4.8
   Compiling convert_case v0.4.0
   Compiling nodrop v0.1.14
   Compiling hashbrown v0.12.3
   Compiling indexmap v2.7.0
   Compiling servo_arc v0.1.1
   Compiling aho-corasick v1.1.3
   Compiling fxhash v0.2.1
   Compiling unic-char-range v0.9.0
   Compiling siphasher v1.0.1
   Compiling thiserror v1.0.69
   Compiling unic-common v0.9.0
   Compiling regex-syntax v0.8.5
   Compiling windows-targets v0.52.6
   Compiling thin-slice v0.1.1
   Compiling unic-ucd-version v0.9.0
   Compiling phf_shared v0.11.3
   Compiling unic-char-property v0.9.0
   Compiling alloc-no-stdlib v2.0.4
   Compiling rand_core v0.5.1
   Compiling serde_json v1.0.140
   Compiling unic-ucd-ident v0.9.0
   Compiling alloc-stdlib v0.2.2
   Compiling windows-sys v0.59.0
   Compiling anyhow v1.0.95
   Compiling rand_pcg v0.2.1
   Compiling dunce v1.0.5
   Compiling shlex v1.3.0
   Compiling brotli-decompressor v4.0.1
   Compiling indexmap v1.9.3
   Compiling percent-encoding v2.3.1
   Compiling camino v1.1.9
   Compiling glob v0.3.2
   Compiling cc v1.2.10
   Compiling form_urlencoded v1.2.1
   Compiling schemars v0.8.21
   Compiling dyn-clone v1.0.17
   Compiling parking_lot v0.12.3
   Compiling windows_x86_64_msvc v0.48.5
   Compiling libc v0.2.169
   Compiling option-ext v0.2.0
   Compiling brotli v7.0.0
   Compiling version_check v0.9.5
   Compiling regex-automata v0.4.9
   Compiling heck v0.5.0
   Compiling windows-link v0.1.1
   Compiling pin-project-lite v0.2.16
   Compiling windows-strings v0.4.0
   Compiling windows-result v0.3.2
   Compiling windows-sys v0.52.0
   Compiling winapi-util v0.1.9
   Compiling dirs-sys v0.5.0
   Compiling futures-core v0.3.31
   Compiling same-file v1.0.6
   Compiling windows-targets v0.48.5
   Compiling dirs v6.0.0
   Compiling slab v0.4.9
   Compiling walkdir v2.5.0
   Compiling windows-sys v0.48.0
   Compiling simd-adler32 v0.3.7
   Compiling typenum v1.17.0
   Compiling vswhom-sys v0.1.2
   Compiling generic-array v0.14.7
   Compiling crc32fast v1.4.2
   Compiling windows_x86_64_msvc v0.53.0
   Compiling adler2 v2.0.0
   Compiling pin-utils v0.1.0
   Compiling futures-task v0.3.31
   Compiling miniz_oxide v0.8.3
   Compiling fdeflate v0.3.7
   Compiling num-conv v0.1.0
   Compiling time-core v0.1.2
   Compiling raw-window-handle v0.6.2
   Compiling powerfmt v0.2.0
   Compiling regex v1.11.1
   Compiling crossbeam-utils v0.8.21
   Compiling mio v1.0.3
   Compiling socket2 v0.5.8
   Compiling flate2 v1.0.35
   Compiling deranged v0.3.11
   Compiling time-macros v0.2.19
   Compiling cookie v0.18.1
   Compiling png v0.17.16
   Compiling unicode-segmentation v1.12.0
   Compiling cfg_aliases v0.2.1
   Compiling tauri-runtime v2.6.0
   Compiling wry v0.51.2
   Compiling softbuffer v0.4.6
   Compiling base64 v0.22.1
   Compiling cpufeatures v0.2.16
   Compiling ico v0.4.0
   Compiling block-buffer v0.10.4
   Compiling vswhom v0.1.0
   Compiling crypto-common v0.1.6
   Compiling crossbeam-channel v0.5.15
   Compiling winreg v0.52.0
   Compiling digest v0.10.7
   Compiling lazy_static v1.5.0
   Compiling tauri-runtime-wry v2.6.0
   Compiling ring v0.17.13
   Compiling quote v1.0.38
   Compiling sha2 v0.10.8
   Compiling mime v0.3.17
   Compiling rustls-pki-types v1.10.1
   Compiling httparse v1.9.5
   Compiling untrusted v0.9.0
   Compiling http-body v1.0.1
   Compiling syn v2.0.96
   Compiling tracing-core v0.1.33
   Compiling try-lock v0.2.5
   Compiling rustls v0.23.21
   Compiling futures-channel v0.3.31
   Compiling num-traits v0.2.19
   Compiling want v0.3.1
   Compiling subtle v2.6.1
   Compiling zeroize v1.8.1
   Compiling tower-service v0.3.3
   Compiling windows-result v0.2.0
   Compiling webpki-roots v0.26.7
   Compiling sync_wrapper v1.0.2
   Compiling bytemuck v1.21.0
   Compiling error-code v3.3.1
   Compiling zip v2.4.1
   Compiling windows-targets v0.53.0
   Compiling byteorder-lite v0.1.0
   Compiling tower-layer v0.3.3
   Compiling futures-sink v0.3.31
   Compiling time v0.3.37
   Compiling windows-version v0.1.2
   Compiling windows-strings v0.1.0
   Compiling rustls-pemfile v2.2.0
   Compiling ipnet v2.10.1
   Compiling window-vibrancy v0.6.0
   Compiling clipboard-win v5.4.0
   Compiling fastrand v2.3.0
   Compiling shared_child v1.0.1
   Compiling os_pipe v1.2.1
   Compiling open v5.3.2
   Compiling encoding_rs v0.8.35
   Compiling windows-registry v0.2.0
   Compiling minisign-verify v0.2.3
   Compiling tempfile v3.15.0
   Compiling image v0.25.5
   Compiling arboard v3.4.1
   Compiling synstructure v0.13.1
   Compiling darling_core v0.20.10
   Compiling serde_derive_internals v0.29.1
   Compiling cssparser v0.27.2
   Compiling html5ever v0.26.0
   Compiling serialize-to-javascript-impl v0.1.1
   Compiling serde_derive v1.0.219
   Compiling zerocopy-derive v0.7.35
   Compiling zerofrom-derive v0.1.5
   Compiling yoke-derive v0.7.5
   Compiling zerovec-derive v0.10.3
   Compiling displaydoc v0.2.5
   Compiling icu_provider_macros v1.5.0
   Compiling thiserror-impl v2.0.11
   Compiling cssparser-macros v0.6.1
   Compiling derive_more v0.99.18
   Compiling thiserror-impl v1.0.69
   Compiling ctor v0.2.9
   Compiling windows-interface v0.59.1
   Compiling windows-implement v0.60.0
   Compiling tokio-macros v2.5.0
   Compiling futures-macro v0.3.31
   Compiling schemars_derive v0.8.21
   Compiling darling_macro v0.20.10
   Compiling futures-util v0.3.31
   Compiling webview2-com-macros v0.8.0
   Compiling serde_repr v0.1.19
   Compiling tracing-attributes v0.1.28
   Compiling tokio v1.44.2
   Compiling http-body-util v0.1.2
   Compiling webview2-com-sys v0.37.0
   Compiling zerocopy v0.7.35
   Compiling ppv-lite86 v0.2.20
   Compiling windows-core v0.61.0
   Compiling darling v0.20.10
   Compiling zerofrom v0.1.5
   Compiling rand_chacha v0.3.1
   Compiling rand_chacha v0.2.2
   Compiling serde_with_macros v3.12.0
   Compiling yoke v0.7.5
   Compiling tracing v0.1.41
   Compiling rand v0.8.5
   Compiling rand v0.7.3
   Compiling windows-future v0.2.0
   Compiling windows-collections v0.2.0
   Compiling windows-numerics v0.2.0
   Compiling zerovec v0.10.4
   Compiling windows v0.61.1
   Compiling phf_generator v0.10.0
   Compiling phf_generator v0.11.3
   Compiling phf_generator v0.8.0
   Compiling string_cache_codegen v0.5.2
   Compiling phf_codegen v0.10.0
   Compiling phf_codegen v0.8.0
   Compiling phf_macros v0.8.0
   Compiling phf_macros v0.11.3
   Compiling selectors v0.22.0
   Compiling markup5ever v0.11.0
   Compiling hyper v1.5.2
   Compiling tokio-util v0.7.13
   Compiling tower v0.5.2
   Compiling tinystr v0.7.6
   Compiling icu_collections v1.5.0
   Compiling icu_locid v1.5.0
   Compiling string_cache v0.8.7
   Compiling serde_spanned v0.6.8
   Compiling toml_datetime v0.6.8
   Compiling dpi v0.1.1
   Compiling uuid v1.12.0
   Compiling erased-serde v0.4.5
   Compiling bitflags v2.8.0
   Compiling icu_provider v1.5.0
   Compiling toml_edit v0.22.22
   Compiling cargo-platform v0.1.9
   Compiling serde_with v3.12.0
   Compiling cfb v0.7.3
   Compiling rustc_version v0.4.1
   Compiling jsonptr v0.6.3
   Compiling serde-untagged v0.1.6
   Compiling icu_locid_transform v1.5.0
   Compiling phf v0.8.0
   Compiling cargo_metadata v0.19.1
   Compiling json-patch v3.0.1
   Compiling infer v0.19.0
   Compiling icu_properties v1.5.1
   Compiling keyboard-types v0.7.0
   Compiling serialize-to-javascript v0.1.1
   Compiling hyper-util v0.1.10
   Compiling serde_urlencoded v0.7.1
   Compiling toml v0.8.19
   Compiling phf v0.11.3
   Compiling embed-resource v3.0.2
   Compiling cargo_toml v0.22.1
   Compiling muda v0.16.1
   Compiling tauri-winres v0.3.0
   Compiling icu_normalizer v1.5.0
   Compiling idna_adapter v1.2.0
   Compiling idna v1.0.3
   Compiling kuchikiki v0.8.2
   Compiling url v2.5.4
   Compiling urlpattern v0.3.0
   Compiling tauri-utils v2.4.0
   Compiling tauri-plugin v2.0.4
   Compiling tauri-build v2.2.0
   Compiling tauri-codegen v2.2.0
error[E0308]: mismatched types
   --> C:\Users\kinso\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-plugin-2.0.4\src\build\mod.rs:140:58
    |
140 |       tauri_utils::plugin::define_global_api_script_path(path);
    |       -------------------------------------------------- ^^^^ expected `&Path`, found `PathBuf`
    |       |
    |       arguments to this function are incorrect
    |
note: function defined here
   --> C:\Users\kinso\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-utils-2.4.0\src\plugin.rs:22:10
    |
22  |   pub fn define_global_api_script_path(path: &Path) {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider borrowing here
    |
140 |       tauri_utils::plugin::define_global_api_script_path(&path);
    |                                                          +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tauri-plugin` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
 ELIFECYCLE  Command failed with exit code 101.
```

### Additional context

I tried to clean the local rust target directory using the `cargo clean` command and rebuilding, but that did not work.
I also tried to purge the `cache`, `index`, and `src` directories in the `./.cargo`, and I am still getting the build error.

The only thing that fixed the error for me was to manually go into the `C:\Users\kinso\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-plugin-2.0.4\src\build\mod.rs` file and manually add the reference operator to the `path` parameter.  

Another thing that I also tried was to create a brand new Tauri application, set the `Cargo.toml` file versions, and set it up to the same as my `Cargo.toml` file, and I built the application.  Unfortunately, the build is not failing.  At this point, I am unsure which direction to take and have no idea why it would fail in my application, but not in the new Tauri test application.

I provided a reproduction list of steps, but unfortunately, that would not help because I cannot offer the application because it is private and for a client.  

But basically, this all started with dependabot creating a pull request to update the `tauri-build` crate from version `v2.2.5` to version `v2.5.1` in the `[build-dependencies]` section of the `Cargo.toml` file and updates the `Cargo.lock` file.

My steps were to check out the branch for the pull request and build the Rust side of the project, but I got the error stated above. I can provide some things.

> [!NOTE]
> Just a heads up, my Rust code is extremely minimal, and I do not think it is an issue. 

**My Application `Cargo.toml`:**
```toml
[package]
name = "app"
version = "1.0.0" # NOTE: This must follow the syntax 'v#.#.#'
description = "SMART-Desk"
authors = ["Calvin Wilkinson (KinsonDigital)"]
license = ""
repository = "https://github.com/EngagedAgility/SMART-Desk"
default-run = "app"
edition = "2021"
rust-version = "1.86.0"
build= "build.rs"

[lib]
name = "smart_desk_lib"
crate-type = ["lib", "cdylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde_json = "^1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.5.1", features = [] }
tauri-plugin-shell = "2.2.1"
tauri-plugin-store = "2.2.0"
tauri-plugin-process = "2.2.1"
tauri-plugin-fs = "2.2.1"
tauri-plugin-clipboard-manager = "2.2.2"
tauri-plugin-updater = "2.7.1"
tauri-plugin-window-state = "2.2.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
```

**Test App `Cargo.toml`:**
```toml
[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
rust-version = "1.86.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
tauri = { version = "2.5.1", features = [] }
tauri-plugin-shell = "2.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```

<details><summary>Rust files for my application</summary>
<p>

These files are literally all of the rust code that I have in the entire application.

`build.rs`
```rs
fn main() {
    tauri_build::build()
}
```

`main.rs`
```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    smart_desk_lib::run()
}
```

`lib.rs`
```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
// #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
// use tauri::{EventLoopMessage, RunEvent};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

</p>
</details>
