### ISSUE TITLE
[bug] Tauri 2.0 Windows Build Failure: windows crate compilation issues

### ISSUE THREAD

**Issue by choruspapa** [tauri-apps/tauri#13638]
### Describe the bug

# Tauri 2.0 Windows Build Failure: windows crate compilation issues

## Problem Description

I'm experiencing build failures when trying to compile a Tauri 2.0 application on Windows. 
The compilation process gets stuck or fails during the `windows` crate compilation phase.

## Environment
- **OS**: Windows 10 (10.0.19045)
- **Rust**: stable-x86_64-pc-windows-msvc
- **Tauri**: 2.0
- **windows crate**: 0.61.3

### Cargo.toml
```toml
[package]
name = "tauri-app"
version = "0.1.0"
description = "Tauri App"
authors = ["myname"]
edition = "2021"

[lib]
name = "edrive_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0", default-features = false, features = [
    "wry",           
    "protocol-asset" 
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Windows dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", default-features = false, features = [
    "Win32_Foundation"
] }

# Windows crate Optimization
[profile.dev.package.windows]
opt-level = 1

[profile.release.package.windows]
opt-level = 2

# build Optimization
[profile.dev]
opt-level = 1
debug = true
incremental = true
codegen-units = 256

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
```

### Environment Variables (PowerShell)
```powershell
$env:RUST_LOG = "debug"
$env:RUST_BACKTRACE = "1"
$env:CARGO_BUILD_JOBS = "1"
$env:RUSTFLAGS = "-C target-feature=+crt-static"
$env:PKG_CONFIG_ALLOW_CROSS = "1"
```

## Build Command Output

When running `cargo build`, the compilation gets stuck at:

```
Compiling windows v0.61.3
     Running `C:\Users\username\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\rustc.exe --crate-name windows --edition=2021 C:\Users\username\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\windows-0.61.3\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=119 --crate-type lib --emit=dep-info,metadata,link -C opt-level=1 -C embed-bitcode=no -C codegen-units=256 -C debuginfo=2 --warn=rust_2018_idioms --warn=unsafe_op_in_unsafe_fn --warn=unexpected_cfgs --warn=missing_docs --check-cfg "cfg(windows_raw_dylib, windows_slim_errors)" -C debug-assertions=on --cfg "feature=\"Win32\"" --cfg "feature=\"Win32_Devices\"" --cfg "feature=\"Win32_Devices_HumanInterfaceDevice\"" --cfg "feature=\"Win32_Foundation\"" --cfg "feature=\"Win32_Globalization\"" --cfg "feature=\"Win32_Graphics\"" --cfg "feature=\"Win32_Graphics_Dwm\"" --cfg "feature=\"Win32_Graphics_Gdi\"" --cfg "feature=\"Win32_System\"" --cfg "feature=\"Win32_System_Com\"" --cfg "feature=\"Win32_System_Com_StructuredStorage\"" --cfg "feature=\"Win32_System_DataExchange\"" --cfg "feature=\"Win32_System_Diagnostics\"" --cfg "feature=\"Win32_System_Diagnostics_Debug\"" --cfg "feature=\"Win32_System_LibraryLoader\"" --cfg "feature=\"Win32_System_Memory\"" --cfg "feature=\"Win32_System_Ole\"" --cfg "feature=\"Win32_System_Registry\"" --cfg "feature=\"Win32_System_SystemInformation\"" --cfg "feature=\"Win32_System_SystemServices\"" --cfg "feature=\"Win32_System_Threading\"" --cfg "feature=\"Win32_System_Variant\"" --cfg "feature=\"Win32_System_WinRT\"" --cfg "feature=\"Win32_System_WindowsProgramming\"" --cfg "feature=\"Win32_UI\"" --cfg "feature=\"Win32_UI_Accessibility\"" --cfg "feature=\"Win32_UI_Controls\"" --cfg "feature=\"Win32_UI_HiDpi\"" --cfg "feature=\"Win32_UI_Input\"" --cfg "feature=\"Win32_UI_Input_Ime\"" --cfg "feature=\"Win32_UI_Input_KeyboardAndMouse\"" --cfg "feature=\"Win32_UI_Input_Pointer\"" --cfg "feature=\"Win32_UI_Input_Touch\"" --cfg "feature=\"Win32_UI_Shell\"" --cfg "feature=\"Win32_UI_Shell_Common\"" --cfg "feature=\"Win32_UI_TextServices\"" --cfg "feature=\"Win32_UI_WindowsAndMessaging\"" --cfg "feature=\"default\"" --cfg "feature=\"std\"" --check-cfg cfg(docsrs,test) --check-cfg "cfg(feature, values(...))" -C metadata=6b7d3a9d9e94518b -C extra-filename=-95a96f55d253e0b5 --out-dir C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps -L dependency=C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps --extern windows_collections=C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps\libwindows_collections-b3d11dfe52adff67.rmeta --extern windows_core=C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps\libwindows_core-279379d09234a7ae.rmeta --extern windows_future=C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps\libwindows_future-978f54360822a7ff.rmeta --extern windows_link=C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps\libwindows_link-c0889709da4f85df.rmeta --extern windows_numerics=C:\Users\username\Documents\workspace\infra\edrive\edrive-app\src-tauri\target\debug\deps\libwindows_numerics-16004866c795fcf6.rmeta --cap-lints allow -C target-feature=+crt-static`
    Building [===============>         ] 311/481: windows
```

## Issues Observed

1. **Feature Bloat**: Despite specifying only `Win32_Foundation` in Cargo.toml, 
the compilation shows many more features being activated 
(Win32_Devices, Win32_Graphics, Win32_System, etc.)

2. **Build Stuck**: The compilation process appears to hang at the windows crate compilation step

3. **Build Performance**: The build thread is limited to 1 (`CARGO_BUILD_JOBS=1`) to reduce resource 
consumption, making the compilation slow but not resource-intensive. 
However, the process still gets stuck during windows crate compilation.

## Attempted Solutions

1. **Minimal Features**: Set `default-features = false` and only include `Win32_Foundation`
2. **Build Optimization**: Set `opt-level = 1` for windows crate in dev profile
3. **Environment Variables**: Set `CARGO_BUILD_JOBS = 1` to reduce parallel compilation
4. **Static Linking**: Added `-C target-feature=+crt-static` to RUSTFLAGS

## Questions

1. **Why are so many features being activated despite minimal configuration?**
   - I only specified `Win32_Foundation` but the build shows dozens of Win32 features

2. **How can I effectively limit the windows crate features?**
   - Is there a way to prevent dependency tree from activating unnecessary features?

3. **What's the best approach to resolve this build failure?**
   - Should I use a different version of the windows crate?
   - Are there alternative approaches to minimize the feature set?

4. **Is this a known issue with Tauri 2.0 + windows crate combination?**
   - Are there specific compatibility issues between these versions?

## Additional Information

- The project is a simple Tauri 2.0 app with minimal dependencies
- I've tried removing `tauri-plugin-opener` to reduce dependencies
- The issue occurs both in debug and release builds
- System has sufficient RAM (64GB) and CPU resources
- Build is configured to use single thread (`CARGO_BUILD_JOBS=1`) to minimize resource usage

Any help or guidance would be greatly appreciated! 

### Reproduction

C:\> pnpm create tauri-app
C:\>cd project_folder
C:\project_folder> pnpm install
Edit cargo.toml for feature optimization
C:\project_folder\src-tauri> cargo build

### Expected behavior

Under release folder, I want see the name of file 'tauri-app.exe'.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 137.0.3296.83
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.87.0 (17067e9ac 2025-05-09)
    ✔ cargo: 1.87.0 (99624be96 2025-05-06)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.18.1
    - pnpm: 10.2.1
    - npm: 11.4.0

[-] Packages
    - tauri 🦀: 2.5.1
    - tauri-build 🦀: 2.2.0
    - wry 🦀: 0.51.2
    - tao 🦀: 0.33.0
    - @tauri-apps/api : 2.5.0
    - @tauri-apps/cli : 2.5.0

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text

```
