### ISSUE TITLE
Transparent window won't update content underneath when using filters.

### ISSUE THREAD

**Issue by mallendeo** [tauri-apps/tauri#1567]
**Describe the bug**
When `backdrop-filter` is applied on any element on a transparent window, the content underneath the window won't get updated unless the window is resized.

**To Reproduce**
1. Create a tauri app with transparent window mode.
2. Apply any `backdrop-filter` to the `body` element.
3. As you move the window, underneath content updates won't be reflected on the background.

**Expected behavior**
The content should be updated without the need of css hacks.

**Screenshots**
The bug:

https://user-images.githubusercontent.com/1578018/115590809-613fc100-a29f-11eb-9203-40c42a0ea08e.mp4

Using a css animation hack/workaround:

```css
[class*="filter-"] {
	animation-duration: 0.1s;
	animation-play-state: running;
	animation-timing-function: linear;
	animation-iteration-count: infinite;
}

.filter-blur { animation-name: blur; }
.filter-sepia { animation-name: sepia; }
.filter-invert { animation-name: invert; }

@keyframes blur { from, to { backdrop-filter: blur(16px); } }
@keyframes sepia { from, to { backdrop-filter: sepia(100%); } }
@keyframes invert { from, to { backdrop-filter: invert(100%); } }
```

https://user-images.githubusercontent.com/1578018/115591172-d1e6dd80-a29f-11eb-907c-8a32abe1c3e6.mp4

Of course this isn't ideal and may cause the battery to drain fast.

**Platform and Versions (please complete the following information):**
OS: Mac OS, version 11.2.3 X64
Node: 15.13.0
NPM: 7.7.6
Yarn: 1.22.10
Rustc: 1.51.0
