### ISSUE TITLE
error: failed to select a version for `webkit2gtk-sys` when trying to use next branch

### ISSUE THREAD

**Issue by barbalex** [tauri-apps/tauri#3226]
### Describe the bug

Updating the tauri dependency from 1.0.0-beta.8 to the next branch creates this error when running `yarn tauri deps update`:

```
PS C:\Users\alexa\kapla> yarn tauri deps update
[tauri]: running deps
 dependency:manager Updating dependencies... +0ms
 app:spawn [sync] Running "rustup update" +107ms

info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.58.0 (02072b482 2022-01-11)

info: cleaning up downloads & tmp directories
 dependency:crates "tauri" is up to date +839ms
 app:spawn [sync] Running "rustup update" +109ms

info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.58.0 (02072b482 2022-01-11)

info: cleaning up downloads & tmp directories
 app:spawn [sync] Running "cargo generate-lockfile" +294ms

    Updating crates.io index
    Updating git repository `https://github.com/tauri-apps/tauri`
    Updating git repository `https://github.com/tauri-apps/tauri-plugin-sql`
    Updating git repository `https://github.com/tauri-apps/wry`
    Updating git repository `https://github.com/tauri-apps/tao`
error: failed to select a version for `webkit2gtk-sys`.
    ... required by package `wry v0.12.0`
    ... which satisfies dependency `tauri-runtime-wry = "^0.2.1"` of package `tauri v1.0.0-beta.8`
    ... which satisfies dependency `tauri = "^1.0.0-beta.8"` of package `tauri-plugin-sql v0.0.0 (https://github.com/tauri-apps/tauri-plugin-sql#330fd795)`
    ... which satisfies git dependency `tauri-plugin-sql` of package `app v0.1.0 (C:\Users\alexa\kapla\src-tauri)`
versions that meet the requirements `^0.14` are: 0.14.0
the package `webkit2gtk-sys` links to the native library `web_kit2`, but it conflicts with a previous package which links to `web_kit2` as well:
package `webkit2gtk-sys v0.16.0`
    ... which satisfies dependency `ffi = "^0.16"` of package `webkit2gtk v0.16.0`
    ... which satisfies dependency `webkit2gtk = "^0.16"` of package `wry v0.12.2 (https://github.com/tauri-apps/wry?rev=3284f8d442978269f7654edbdfc9bc51022eaa40#3284f8d4)`
    ... which satisfies git dependency `wry` of package `tauri-runtime-wry v0.2.1 (https://github.com/tauri-apps/tauri?branch=next#ab7d3b51)`
    ... which satisfies git dependency `tauri-runtime-wry` of package `tauri v1.0.0-beta.8 (https://github.com/tauri-apps/tauri?branch=next#ab7d3b51)`
    ... which satisfies git dependency `tauri` of package `app v0.1.0 (C:\Users\alexa\kapla\src-tauri)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='webkit2gtk-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.
failed to select a version for `webkit2gtk-sys` which could resolve this conflict

 app:spawn ⚠️  Command "cargo" failed with exit code: 101 +0ms
```

### Reproduction

I changed my Cargo.toml from:

```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
tauri-plugin-sql = { git = "https://github.com/tauri-apps/tauri-plugin-sql", features = [ "sqlite" ] }
whoami = "1.2.1"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
```
to:
```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = [ "api-all" ] }
tauri-plugin-sql = { git = "https://github.com/tauri-apps/tauri-plugin-sql", features = [ "sqlite" ] }
whoami = "1.2.1"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
```

The reason I did this was to get the `'tauri://close-requested'`-event to run without the app exiting too early.

### Expected behavior

The update works.

### Platform and versions

```shell
PS C:\Users\alexa\kapla> yarn tauri info
 app:spawn Running "C:\Users\alexa\kapla\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.22000 X64
Webview2 - 97.0.1072.55

Node.js environment
  Node.js - 17.3.1
  @tauri-apps/cli - 1.0.0-beta.10  @tauri-apps/api - Not installed

Global packages
  npm - 8.3.0
  yarn - 3.1.1

Rust environment
  rustc - 1.58.0
  cargo - 1.58.0

App directory structure
/.git
/.yarn
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```
