### ISSUE TITLE
[bug] failed to run custom build command for `gdk-sys v0.15.1`

### ISSUE THREAD

**Issue by ankitpatial** [tauri-apps/tauri#3856]
### Describe the bug

Fails to build/run tauri app on ubuntu machine.
> yarn tauri dev

I have also tried
> cargo install tauri-cli --git https://github.com/tauri-apps/tauri
> cargo tauri build 
but still issue is same.

### Reproduction

1. go to source dir
2. yarn tauri dev

### Expected behavior

Tauri app must open on devleopment machine.

### Platform and versions

```shell
OS: Ubuntu 20.04.4 LTS
Rust: rustc 1.59.0 (9d1b2106e 2022-02-23)
Node: v16.14.2
```

### Stack trace

```shell
error: failed to run custom build command for `gdk-sys v0.15.1`

Caused by:
  process didn't exit successfully: `my-app/src-tauri/target/debug/build/gdk-sys-a861ad546eb74735/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GDK_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "gdk-3.0" "gdk-3.0 >= 3.22"` did not exit successfully: exit status: 1
  error: could not find system library 'gdk-3.0' required by the 'gdk-sys' crate

  --- stderr
  Package gdk-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gdk-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gdk-3.0' found
  Package gdk-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gdk-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gdk-3.0' found

warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Additional context

Installed packages

sudo apt update && sudo apt install \
	libwebkit2gtk-4.0-dev \
        build-essential \
        curl \
        wget \
        libglib2.0-dev \
        libssl-dev \
        libgtk-3-dev \
        libappindicator3-dev \
        librsvg2-dev \
        libappindicator-dev \
        libgdk3.0-cil libatk1.0-dev

**Comment by lucasfernog** [comment]
Are you sure `libgtk-3-dev` was installed without any errors? It should just work with the dependencies properly installed.

**Comment by FabianLars** [comment]
Either what Lucas said, or you're using homebrew whose own pkg-config breaks every pipeline lol (cause it prevents finding system packages). In that case the only real option is to uninstall homebrew.

**Comment by ankitpatial** [comment]
Thank you @lucasfernog  & @FabianLars for quick help.

Yes culprit was homebrew on linux. I removed homebrew and everything seems normal now.
I was not hoping homebrew to screw it.

Again, Thank you guys!

**Comment by Sewdohe** [comment]
I'm having the same issue on Zorin (debian based) as OP here, only I'm only having the issue with 1 of my Tauri projects...I have another that is launching just fine, and libgtk-3-dev is installed on my machine

**Comment by ales-tsurko** [comment]
I have this issue in github actions. My config is:

```
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-20.04]

    steps:
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --verbose
      - name: install app dependencies and build it
        run: |
          cd gui
          npm i && npm run build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
