### ISSUE TITLE
[feat] expose `tao::Window::set_cursor_position`

### ISSUE THREAD

**Issue by CaptainTux** [tauri-apps/tauri#3890]
### Describe the problem

I want to reposition the mouse pointer within the tauri window.
I have read that `winit` has functions to do that, so I would assume `tao` can also do that.
Since tao is not exposed by tauri, I cannot use those capabilities.

### Describe the solution you'd like

I would like an API function where I can pass coordinates relative to the top left corner of the tauri window which would reposition the mouse pointer.
For example, if I would do `set_pointer_position(0,0)`, the cursor would jump to the top left corner.

### Alternatives considered

I have created a custom tauri command using `winapi`, which looks like this:
```rust
#[tauri::command]
fn set_pointer_position(window: tauri::Window, x: i32, y: i32) {
  let inner_size = window.inner_size().unwrap();
  let outer_size = window.outer_size().unwrap();
  let pos = window.inner_position().unwrap();
  unsafe {
    if winapi::um::winuser::SetPhysicalCursorPos(pos.x + x, pos.y + y + (outer_size.height as i32 - inner_size.height as i32)) == 0 {
      panic!("SetCursorPos failed");
    }
  }
}
```

**Comment by CaptainTux** [comment]
I have tried using the exposed API function.
unfortunately, it hasn't worked for me.
I am on arch linux, kernel 5.17.3-arch1-1 build, and 
`npm run tauri info` yields this:
```
> my_project@0.1.1 tauri
> tauri "info"


Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 17.9.0
  › npm: 8.7.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri#8e00f0904c9d7385a5fc79a32b3bb2397699c305 (1.0.0-rc.6),
  › tauri-build [RUST]: git+https://github.com/tauri-apps/tauri#8e00f0904c9d7385a5fc79a32b3bb2397699c305 (1.0.0-rc.5),
  › tao [RUST]: 0.8.2,
  › wry [RUST]: 0.15.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React
```
my tauri command looks like this: 
```rust
#[tauri::command]
fn set_pointer_position(window: tauri::Window, x: i32, y: i32) {
    let result = window.set_cursor_position(tauri::Position::Physical(tauri::PhysicalPosition{x, y}));
    if result.is_err() {
        panic!("setting cursor failed");
    }
    println!("cursor set {} {}", x, y);
}
```
and the console output is as expected.
```toml
// relevant cargo.toml data
[build-dependencies]
tauri-build = { git = "https://github.com/tauri-apps/tauri", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { git = "https://github.com/tauri-apps/tauri", features = ["api-all"] }
winapi = { version = "0.3.9" }
mouse-rs = { version = "0.4" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```
what is the problem here?
I am running the app with `cargo run --no-default-features` as was recommended in the discord server after `npm run start`.
I haven't tried it on Windows yet, planning to do that this weekend.

**Comment by lucasfernog** [comment]
It is not implemented yet on Linux, see https://github.com/tauri-apps/tao/blob/edf6e766704a3f10d62673e6be6f168a1daa0b15/src/platform_impl/linux/window.rs#L565

I documented this in the function but you'd need to build the docs manually to see it.

**Comment by amrbashir** [comment]
@CaptainTux I plan to implement this for linux soon. In a week maybe.

**Comment by amrbashir** [comment]
I guess I lied 😁, here it is https://github.com/tauri-apps/tao/pull/373 if you want to test it and give feedback.

**Comment by lucasfernog** [comment]
`set_cursor_grab` doesn't exist on Linux too, maybe we could just set the cursor icon to grab?

**Comment by lucasfernog** [comment]
You can try it now by adding this to your Cargo.toml:

```toml
[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao" }
```

Don't forget to run `cd src-tauri && cargo update`.
