### ISSUE TITLE
[bug] weird cursor while dragging the element which has `data-tauri-drag-region` attribute

### ISSUE THREAD

**Issue by percy507** [tauri-apps/tauri#4059]
### Describe the bug

> I am not sure this is a bug or just a missing part of document.

Before adding the `draggable` attribute, the cursor is not the wanted one while dragging.

![cbca4366-2fe0-4e15-9fc7-1138d5645006 (1)](https://user-images.githubusercontent.com/18365078/166742458-971b1b16-081c-4e3f-b22b-52ed5e3d5cf9.gif)

### Platform and versions

```shell
Environment
  › OS: Mac OS 11.6.0 X64
  › Node.js: 16.10.0
  › npm: 7.24.0
  › pnpm: 6.16.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.9)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.4)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.4,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,
```

**Comment by Laegel** [comment]
Hey @percy507 , that doesn't look like a bug but rather something we're not handling (yet?). 
You may customize your cursor with the following CSS properties:

```css
[data-tauri-drag-region] {
  cursor: move; /* Not all browsers support "grab" */
  cursor: grab;
  cursor: -webkit-grab;
}

[data-tauri-drag-region]:active {
  cursor: grabbing;
  cursor: -webkit-grabbing;
}
```
