### ISSUE TITLE
[bug] tauri rc.11 from crates.io doesn't detect development mode

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#4178]
### Describe the bug

When I pull tauri from crates.io it fails to compile the app with the following error
```
error: proc macro panicked
  --> desktop/app/src/main.rs:79:10
   |
79 |     .run(tauri::generate_context!())
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: The `distDir` configuration is set to `"../../plz-out/gen/frontend/dist/client"` but this path doesn't exist
```
When I build my frontend first (it get's placed into `../../plz-out/gen/frontend/dist/client`) the app builds fine, but includes the *static assets* it doesn't connect to the development server even though it starts the server just fine.

It's also important to note that **only the crates.io version has this issue** when pulled in from git or local path the build behaves as expected. Additionally I can't replicate this bug with project freshly created by cta

### Reproduction

I don't even know if this is reproducible, but here goes:
1. Make sure the `distDir` is removed
2. Run `tauri dev`
3. See Error:
   ```
   error: proc macro panicked
     --> desktop/app/src/main.rs:79:10
        |
   79 |     .run(tauri::generate_context!())
        |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: message: The `distDir` configuration is set to `"../../plz-out/gen/frontend/dist/client"` but this path doesn't exist
   ```

### Expected behavior

Both the version pulled from crates.io and the version from git should behave the same and run the app in dev mode without a problem.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 7.0.1
  › yarn: 3.2.1
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.11
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.11 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: default-src 'self' style-src 'self' 'unsafe-inline' connect-src http://localhost:55001
  › distDir: ../../plz-out/gen/frontend/dist/client
  › devPath: http://localhost:3000/
  › bundler: Rollup

App directory structure
  ├─ .config
  ├─ .husky
  ├─ .yarn
  ├─ infra
  ├─ frontend
  ├─ proto
  ├─ plz-out
  ├─ target
  ├─ node_modules
  ├─ desktop
  ├─ backend
  ├─ docs
  ├─ third_party
  ├─ graphql
  ├─ scripts
  ├─ .github
  ├─ .plz-cache
  ├─ build
  ├─ .git
  └─ .vscode
  
  Note that I have a **very uncommon** repo structure, where `desktop/app` is the rust app and `frontend/app` is the JS frontend
```

**Comment by lucasfernog** [comment]
@JonasKruckenberg can you share your Cargo.toml? maybe you're always enabling the `custom-protocol` feature. I couldnt reproduce with the api example, maybe you could share the repo later if we can't spot a manifest problem.

**Comment by JonasKruckenberg** [comment]
That's the Cargo.toml, I made sure to keep the feature thingy at the bottom so everything should be okay?

```toml
[package]
name = "mintter"
version = "0.0.0" # don't touch! This gets overriden with the correct version by CI.
description = "A publishing platform where other content creators can reuse your content keeping your authorship and royalties."
authors = ["The mintter team"]
license = ""
repository = ""
default-run = "mintter"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.9", features = [] }

[dependencies]
tauri = { git = "https://github.com/tauri-apps/tauri", rev = "356b3e1c467d5120f7600717dfff08d8dbedcc04", features = ["ayatana-tray", "cli", "shell-execute", "shell-open", "system-tray", "window-maximize", "window-start-dragging", "window-unmaximize"] }
# tauri = { version = "1.0.0-rc.11", features = ["ayatana-tray", "cli", "shell-execute", "shell-open", "system-tray", "window-maximize", "window-start-dragging", "window-unmaximize"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/tauri-plugin-log", rev = "0e993f8ded5867772b29ca7aee5bc5594aba6fb9", features = ["colored"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store", rev = "5726952177b88d1d10063cdf8e7506bac84772cf" }
tokio = { version = "1.18.2", features = ["full"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
log = "0.4.17"
anyhow = "1.0.57"
env_logger = "0.9.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
# cap-std = "0.24.3"
# extension-host = { path = "../extension-host" }
# common = { path = "../common" }

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24.0"
objc = "0.2.7"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```

The repo is private so I can't really share that easily :/
