### ISSUE TITLE
Problem with systemTray Icon

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#4347]
My system tray icon is never displayed.
I did all things as well and test on both Ubuntu 20 and 22 but it made no difference!

this is my code:
```rs
use tauri::{CustomMenuItem, SystemTrayMenu, SystemTray};

fn main() {

    let quit = CustomMenuItem::new("quit".to_string(), "Quit");

    let tray_menu = SystemTrayMenu::new().add_item(quit);
    let tray = SystemTray::new().with_menu(tray_menu);

    tauri::Builder::default()
        .system_tray(tray)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

my tauri.conf.json:
```json
{
  "package": {
    "productName": "koruma",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "build",
    "devPath": "http://localhost:3000",
    "beforeDevCommand": "",
    "beforeBuildCommand": ""
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icon.png"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "macOS": {
        "frameworks": [],
        "useBootstrapper": false,
        "exceptionDomain": "",
        "signingIdentity": null,
        "providerShortName": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "allowlist": {
      "all": true
    },
    "windows": [
    ],
    "systemTray": {
      "iconPath": "icon.png",
      "iconAsTemplate": true
    },
    "security": {
      "csp": null
    }
  }
}
```

tauri info:
```
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.15
  › @tauri-apps/api [NPM]: 1.0.0-rc.7
  › tauri [RUST]: 1.0.0-rc.16 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ src-tauri
  └─ node_modules
```

The problem is that icon in system Tray not displayed and three-dot is displayed instead!
my icon file also is for tauri (icon.png)

**Comment by amrbashir** [comment]
Is the icons next to tauri.conf.json? or how does your project look like?

**Comment by rdwnsjjd** [comment]
```bash
user@user:~/Documents/project$ ls -a
.  ..  build  build.rs  Cargo.lock  Cargo.toml  .git  .gitignore  icon.png  public  src  src-tauri  target  tauri.conf.json
```

**Comment by rdwnsjjd** [comment]
Cargo.toml

```toml
[package]
name    = "project"
edition = "2018"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.5", features = ["api-all", "system-tray"] }
tao = "0.7.0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
```
