### ISSUE TITLE
Problem with closing window

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#4365]
I have a system tray app that goes up and then it makes some other windows.
I expect when `close` function of one of the windows is called, just that window going to be closed.
but all the app will closes when one of them closes. why?
( the `close` function will called using events and by UI. for minimalism I just call it after 5 sec of window creation.) 

my `main.rs`
```rs
use std::{process, path::PathBuf, thread, time::Duration};
use tauri::{SystemTrayMenu, CustomMenuItem, SystemTray, Builder, SystemTrayEvent, Window, App};

fn main() {

    let callback = |app: &mut App| {
        let app_handle = app.handle();

        let mut new_win_builder = Window::builder(
            &app_handle,
            "Hello", 
            tauri::WindowUrl::App(PathBuf::new())
        );

        new_win_builder = new_win_builder.transparent(true);
        new_win_builder = new_win_builder.focus();
        new_win_builder = new_win_builder.decorations(false);
        new_win_builder = new_win_builder.resizable(false);
        new_win_builder = new_win_builder.fullscreen(false);
        new_win_builder = new_win_builder.position(20000.0, 10000.0);
        new_win_builder = new_win_builder.inner_size(410.0, 200.0);

        println!("Creating new window with name `Hello`!");
        let new_win = new_win_builder.build().unwrap();

        thread::sleep(Duration::from_millis(5000));
        new_win.close().unwrap();

        Ok(())
    };

    let tray_menu = SystemTrayMenu::new()
    .add_item(CustomMenuItem::new("exit".to_string(), "Exit"));

    let system_tray = SystemTray::new().with_menu(tray_menu); //.with_icon(tray_icon);
    Builder::system_tray(Builder::default(), system_tray)
    .setup(callback)
    .on_system_tray_event(move |_app, event| {
        if let SystemTrayEvent::MenuItemClick {id, .. } = event {
            match &id[..] {
                "exit" => {
                    process::exit(0);
                },
                _ => {println!("Unknown item!")}
            }
        }
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

my `Cargo.toml`:
```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.14" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.16", features = ["api-all", "system-tray"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```

my `tauri info`:
```
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.15
  › @tauri-apps/api [NPM]: 1.0.0-rc.7
  › tauri [RUST]: 1.0.0-rc.16 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ src-tauri
  └─ node_modules
```

my project org:
```bash
user@user:~/Documents/project$ ls -a
.   ..   build  Cargo.toml    src   tauri.conf.json   Cargo.lock   icons  public
```
