### ISSUE TITLE
[bug] Github actions all platform builds fail with MODULE NOT FIND

### ISSUE THREAD

**Issue by Flavsditz** [tauri-apps/tauri#4597]
### Describe the bug

Using the GitHub action provided on the website (with just a change to use NPM instead of Yarn) here:

```
name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Node.js setup
      uses: actions/setup-node@v1
      with:
        node-version: 16
        
    - name: Rust setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
        
    - name: Install app dependencies and build it
      run: npm install && npm run build
      
    - name: Build the app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
```

I've left it running and initially I got an error on the **windows** pipeline due to prettier that got solved by adding a `.gitattributes` file to the root of the project with `* text=auto eol=lf`. (I would be willing to make an MR to get this info in the docs if you judge it necessary - I know it is specific to prettier, but it could avoid other problems due to line-endings)

All other pipelines seemed ok but I later found out they all get stuck (and consume minutes) on the **build step** with the following error:

```
Run tauri-apps/tauri-action@v0
  
running npx [ 'run', 'tauri:build' ]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN exec The following package was not found and will be installed: run
Watching D:\a\test-tauri-app\test-tauri-app and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./dist\css\app.6cd52001.css ; has ignored extension
Found & ignored ./src\assets\style\tailwind.css ; has ignored extension
Starting: tauri:build
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'D:\a\test-tauri-app\test-tauri-app\tauri:build'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

It is my first experience with Github Actions and I have no idea what this error is pointing to.

### Platform and versions

```shell
The Platform and version is from the gitlab pipelines
```
