### ISSUE TITLE
[bug] HTTP 100 response inconsistent between default and "reqwest-client"

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/tauri#4796]
### Describe the bug

Depending on whether `Cargo.toml` > `tauri` > `features` contains `["api-all"]` or `["api-all", "reqwest-client"]`, the `http` API behaves inconsistently when receiving an HTTP 100 response.

### Reproduction

Make an `http` request that will return status code `100`.

### Expected behavior

Both configurations behaves consistently (either with a success or error response).

### Platform and versions

```
Environment
  › OS: Ubuntu 21.10 X64
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:1234/

App directory structure
  ├─ src
  ├─ .git
  ├─ .parcel-cache
  ├─ src-tauri
  ├─ .idea
  ├─ dist
  └─ node_modules
```

### Stack trace

```
Network Error: error sending request for url (http://localhost:5678/100): connection closed before message completed
```

### Additional context

Here are screenshots of this inconsistency being spotted while running [`axios-tauri-adapter-test`](https://git.kaki87.net/KaKi87/axios-tauri-adapter-test) :

![](https://cdn.discordapp.com/attachments/997089807689842798/997153507943661619/Screenshot_from_2022-07-14_16-50-53.png)

![](https://cdn.discordapp.com/attachments/997089807689842798/997153574536609912/Screenshot_from_2022-07-14_16-49-45.png)

**Comment by lucasfernog** [comment]
This looks like a hyper issue (hyper is used by reqwest). See https://github.com/hyperium/hyper/issues/2565 and https://github.com/hyperium/hyper/issues/2743

There's not much we can do, the alternative is already there if you can use attohttpc.

**Comment by KaKi87** [comment]
Is it possible to know from JS what Rust client is used ? (so I could perform conditional assertion)

**Comment by FabianLars** [comment]
~~That's only accessible in rust. So you either have to send that info from the rust side to js,~~ NVM it isn't unless you can parse the cargo.toml file.
 or idk do a dummy request and check the responses (_if_ the clients do something differently that is).

(I'd still like to merge both clients into a custom hyper one, but so much could go wrong 😅)

**Comment by KaKi87** [comment]
So, using [`toml`](toml),
This :
```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
```
Turns into this :
```json
{
    "package": {
        "name": "app",
        "version": "0.1.0",
        "description": "A Tauri App",
        "authors": [
            "you"
        ],
        "license": "",
        "repository": "",
        "default-run": "app",
        "edition": "2018",
        "build": "src/build.rs"
    },
    "build-dependencies": {
        "tauri-build": {
            "version": "1.0.0-beta.4",
            "features": []
        }
    },
    "dependencies": {
        "serde_json": "1.0",
        "serde": {
            "version": "1.0",
            "features": [
                "derive"
            ]
        },
        "tauri": {
            "version": "1.0.0-beta.8",
            "features": [
                "api-all"
            ]
        }
    },
    "features": {
        "default": [
            "custom-protocol"
        ],
        "custom-protocol": [
            "tauri/custom-protocol"
        ]
    }
}
```
And this :
```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all", "reqwest-client"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
```
Into this :
```json
{
    "package": {
        "name": "app",
        "version": "0.1.0",
        "description": "A Tauri App",
        "authors": [
            "you"
        ],
        "license": "",
        "repository": "",
        "default-run": "app",
        "edition": "2018",
        "build": "src/build.rs"
    },
    "build-dependencies": {
        "tauri-build": {
            "version": "1.0.0-beta.4",
            "features": []
        }
    },
    "dependencies": {
        "serde_json": "1.0",
        "serde": {
            "version": "1.0",
            "features": [
                "derive"
            ]
        },
        "tauri": {
            "version": "1.0.0-beta.8",
            "features": [
                "api-all",
                "reqwest-client"
            ]
        }
    },
    "features": {
        "default": [
            "custom-protocol"
        ],
        "custom-protocol": [
            "tauri/custom-protocol"
        ]
    }
}
```
Do I only have to check whether `dependencies.tauri.features` includes `reqwest-client`, or are there other possible configurations, like maybe one that explicitly enables the default client ?

Thanks

**Comment by FabianLars** [comment]
If the package can handle this syntax too (it's part of the toml standard, so packages _should_ support it)
```
[dependencies.tauri]
version = ""
features = []
```
then you should be covered.

The client is at the moment _only_ changeable via the reqwest-client flag.
the only thing that could be a problem is if users create their own feature flags that enable it, like we do here with the custom-protocol 🤔

**Comment by KaKi87** [comment]
> If the package can handle this syntax too (it's part of the toml standard, so packages _should_ support it)
> 
> ```
> [dependencies.tauri]
> version = ""
> features = []
> ```
> 
> then you should be covered.

That works too, thanks.
> The client is at the moment _only_ changeable via the reqwest-client flag.

Alright !
> the only thing that could be a problem is if users create their own feature flags that enable it, like we do here with the custom-protocol thinking

Something like this ?
```toml
[features]
default = [ "custom-protocol", "foobar" ]
custom-protocol = [ "tauri/custom-protocol" ]
foobar = ["reqwest-client"]
```
If yes, I'm pretty sure I can parse it as well, using some loops.
