### ISSUE TITLE
[bug] Mac build using tauri-action fails: "Failed to run codesign" 

### ISSUE THREAD

**Issue by salmenf** [tauri-apps/tauri#4944]
### Describe the bug

I tried following the guide for [Mac code signing](https://tauri.app/v1/guides/distribution/sign-macos/) in the docs.

All secrets are set in Github (secrets like the Github token work just fine). I am unsure how to debug this further without the output from `codesign`, it would be helpful to get this in the logs.
I suspect the signing identity is an issue: I was not sure what to put here when running this as an action, since the guide says about the APPLE_CERTIFICATE variable: "Useful if you don't have the certificate on the keychain". I just put an arbitrary string.

Sorry to provide such limited information, it's hard to write a good issue about this without leaking my credentials. ;)

### Platform and versions

Using `macos-latest` runner on Github.

### Stack trace

```shell
Signing [...] with identity "***"
        Info setup keychain from environment variables...
       Error failed to bundle project: failed to sign app: failed to sign app: `failed to run codesign`
```

### Additional context

Github workflow used:
```
name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install tauri dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: import windows certificate (windows only)
        if: matrix.platform == 'windows-latest'
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        run: |
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate/tempCert.txt -Value $env:WINDOWS_CERTIFICATE
          certutil -decode certificate/tempCert.txt certificate/certificate.pfx
          Remove-Item -path certificate -include tempCert.txt
          Import-PfxCertificate -FilePath certificate/certificate.pfx -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString -String $env:WINDOWS_CERTIFICATE_PASSWORD -Force -AsPlainText)
      
      - name: Install web dependencies
        run: npm install
        
      - name: Build web
        run: npm run build-web
        
      - name: Create binaries
        run: node ./createbinaries.js

      - name: Prepare static
        run: node ./preparestatic.js

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          ENABLE_CODE_SIGNING: "${{ secrets.APPLE_CERTIFICATE }}"
          APPLE_CERTIFICATE: "${{ secrets.APPLE_CERTIFICATE }}"
          APPLE_CERTIFICATE_PASSWORD: "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}"
          APPLE_SIGNING_IDENTITY: "${{ secrets.SIGNING_IDENTITY }}"
          APPLE_ID: "${{ secrets.APPLE_ID }}"
          APPLE_PASSWORD: "${{ secrets.APPLE_PASSWORD }}"
        with:
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
```
