### ISSUE TITLE
[bug] Cargo workspace breaks mobile bundler

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#5865]
### Describe the bug

I recently started adding a top-level cargo workspace to all my Tauri apps, so that regular cargo commands work without annoying `cd src-tauri`.

This breaks the mobile bundler however as it apparently expects a hard-coded `target`path for the dylib.

### Reproduction

1. Create a Tauri app that has mobile support (so through `ppm crate vite` and `cargo tauri init`)
2. Add a top level cargo workspace
   ```toml
   [workspace]
   members = ["src-tauri"]
   ```
3. See the error `ld: warning: directory not found for option '-L/Users/jonaskruckenberg/Documents/GitHub/elk-desktop/src-tauri/target/aarch64-apple-ios-sim/debug'` it is looking in the wrong path for the dylib

### Expected behavior

The mobile bundler should use the cargo apis (`cargo metadata` maybe?) to figure out the correct target directory

### Platform and versions

```
Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.18.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.1 (1.2.2, 2.0.0-alpha.1),
  › tauri-build [RUST]: 2.0.0-alpha.0,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.23.1,

App
  › build-type: bundle
  › CSP: style-src 'self'; media-src https:; connect-src https: wss:; font-src 'self'; default-src 'none'; img-src 'self' data: https:
  › distDir: ../elk/.output/public
  › devPath: http://localhost:5314/

App directory structure
  ├─ target
  ├─ elk
  ├─ .github
  ├─ src-tauri
  └─ .git

iOS
  › Teams: None
```

### Stack trace

```shell
Ld /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Products/debug-iphonesimulator/app.app/app normal (in target 'app_iOS' from project 'app')
    cd /Users/jonaskruckenberg/Documents/GitHub/elk-desktop/src-tauri/gen/apple
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-sim-apple-ios9.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk -L/Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/EagerLinkingTBDs -L/Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Products/debug-iphonesimulator -L/Users/jonaskruckenberg/Documents/GitHub/elk-desktop/src-tauri/target/aarch64-apple-ios-sim/debug -F/Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/EagerLinkingTBDs -F/Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Products/debug-iphonesimulator -F. -filelist /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/app.build/debug-iphonesimulator/app_iOS.build/Objects-normal/arm64-sim/app.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/app.build/debug-iphonesimulator/app_iOS.build/Objects-normal/arm64-sim/app_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/app.build/debug-iphonesimulator/app_iOS.build/app.app-Simulated.xcent -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __ents_der -Xlinker /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/app.build/debug-iphonesimulator/app_iOS.build/app.app-Simulated.xcent.der -lapp -framework CoreGraphics -framework Metal -framework MetalKit -framework QuartzCore -framework Security -framework UIKit -framework WebKit -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Intermediates.noindex/app.build/debug-iphonesimulator/app_iOS.build/Objects-normal/arm64-sim/app_dependency_info.dat -o /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Products/debug-iphonesimulator/app.app/app
ld: warning: directory not found for option '-L/Users/jonaskruckenberg/Documents/GitHub/elk-desktop/src-tauri/target/aarch64-apple-ios-sim/debug'
ld: library not found for -lapp
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
        Ld /Users/jonaskruckenberg/Library/Developer/Xcode/DerivedData/app-elzodwdekrmvyqaltibljffxgybm/Build/Products/debug-iphonesimulator/app.app/app normal (in target 'app_iOS' from project 'app')
(1 failure)
       Error Command "xcodebuild -scheme app_iOS -workspace /Users/jonaskruckenberg/Documents/GitHub/elk-desktop/src-tauri/gen/apple/app.xcodeproj/project.xcworkspace/ -sdk iphonesimulator -configuration debug -arch arm64-sim -allowProvisioningUpdates build" didn't complete successfully, exiting with code 65.
```

**Comment by FabianLars** [comment]
Same for the `build.target-dir` config btw

**Comment by lucasfernog** [comment]
The iOS usage was fixed by #5807 since we call the target detection used on desktop to move the artifacts to the Xcode project. I'll work on fixing it for Android.

**Comment by penx** [comment]
> The iOS usage was fixed by #5807


@lucasfernog I'm getting "ld: library not found for -lapp" when running `yarn tauri ios dev`


This is a new project, using vite, following the guide today and with the following versions

rust@1.64
tauri@2.0.0-alpha.3
tauri-cli-ios@2.0.0-alpha.2
tauri-build@2.0.0-alpha.1
@tauri-apps/ap@2.0.0-alpha.0
@tauri-apps/cli@2.0.0-alpha.2

```console
yarn add -D @tauri-apps/cli@next @tauri-apps/api@next
yarn tauri init
TAURI_APPLE_DEVELOPMENT_TEAM=XXX yarn tauri ios init
yarn tauri ios dev
```

(yarn tauri dev runs on macOS fine)

**Comment by lucasfernog** [comment]
Did you add the [lib] section in Cargo.toml?

**Comment by penx** [comment]
I guess I've missed some setup instructions? I've been following

- https://tauri.app/blog/2022/12/09/tauri-mobile-alpha
- https://tauri.app/v1/guides/getting-started/setup/integrate

I have the folllowing in lib, which was generated:

```toml
[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
```

And this issue was the only result for this error :)

**Comment by penx** [comment]
Full Cargo.toml

```toml
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha.3", features = [] }

[features]
default = []
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```
