### ISSUE TITLE
[bug] Crash Mobile on TauriActivity.create()

### ISSUE THREAD

**Issue by alexandru0-dev** [tauri-apps/tauri#6235]
### Describe the bug

successfully compiling for mobile aarch_64, but once run, it crashed.
successfully working on linux_x86_64_gnu

### Expected behavior

don't crash and run the application

### Platform and versions
```
Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 16.19.0
  › npm: 9.1.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.3,
  › tauri-build [RUST]: 2.0.0-alpha.1,
  › tao [RUST]: 0.17.0,
  › wry [RUST]: 0.26.0,
```

### Stack trace

```shell
2-10 05:32:19.838 24275 24275 E com.tauri.api: No implementation found for void com.tauri.api.TauriActivity.create(com.tauri.api.TauriActivity) (tried Java_com_tauri_api_TauriActivity_create and Java_com_tauri_api_TauriActivity_create__Lcom_tauri_api_TauriActivity_2)
--------- beginning of crash
02-10 05:32:19.839 24275 24275 E AndroidRuntime: FATAL EXCEPTION: main
02-10 05:32:19.839 24275 24275 E AndroidRuntime: Process: com.tauri.api, PID: 24275
02-10 05:32:19.839 24275 24275 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.tauri.api.TauriActivity.create(com.tauri.api.TauriActivity) (tried Java_com_tauri_api_TauriActivity_create and Java_com_tauri_api_TauriActivity_create__Lcom_tauri_api_TauriActivity_2)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at com.tauri.api.TauriActivity.create(Native Method)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at com.tauri.api.TauriActivity.onCreate(TauriActivity.kt:52)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8129)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8109)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
02-10 05:32:19.839 24275 24275 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Additional context

trying to make some tests. This is the second time that happened to me. this was the result trying to adapt the `example/api` for mobile

updated Cargo.toml from example/api:
```toml
[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.59"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.1", features = ["codegen", "isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tiny_http = "0.12.0"
tauri = { tauri-build = "2.0.0-alpha.1", features = ["api-all", "cli", "global-shortcut", "http-multipart", "icon-ico", "icon-png", "isolation", "macos-private-api", "native-tls-vendored", "reqwest-client", "system-tray", "updater", "windows7-compat"] }


[target."cfg(target_os = \"windows\")".dependencies]
window-vibrancy = "0.3.2"
window-shadows= "0.2.1"

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
log = "0.4"
tauri-runtime-wry = { version = "0.13.0-alpha.1" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.12.0"
jni = "0.20.0"
paste = "1.0"

[target.'cfg(target_os = "ios")'.dependencies]
mobile-entry-point = "0.1.1"
env_logger = "0.10.0"

[features]
custom-protocol = [ "tauri/custom-protocol" ]
```
