### ISSUE TITLE
[bug] proguard rules android

### ISSUE THREAD

**Issue by kilisio** [tauri-apps/tauri#6428]
### Describe the bug

isMinifyEnabled = true in build.gradle.kts seems to cause app startup crashes in android release apk build, not sure which proguard rule to include or change to prevent this. 

I opened a discord discussion in support tab of the same name:
`https://discord.com/channels/616186924390023171/1084443958152802354`

### Platform and versions

```text
Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 19.7.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
```

### Additional context

I installed tauri-cli using: 
```bash
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --rev 8631eec
```

my cargo.toml:
```toml
[build-dependencies.tauri-build]
features = []
git = "https://github.com/tauri-apps/tauri"
rev = "8631eec"

[dependencies]
anyhow = "1.0.56"
log = "0.4.11"
serde_json = "1.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.tauri]
features = ["api-all", "windows7-compat"]
git = "https://github.com/tauri-apps/tauri"
rev = "8631eec"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[package]
authors = ["kilisio (kilisio.deno.dev)"]
description = ""
edition = "2021"
license = "MIT"
name = "appname"
rust-version = "1.59"
version = "2.1.2"
[target."cfg(not(any(target_os = \"android\", target_os = \"windows\")))".dependencies]
core-foundation = "0.9.3"
env_logger = "0.9.0"
mobile-entry-point = "0.1.0"
[target."cfg(target_os = \"android\")".dependencies]
android_logger = "0.9.0"
jni = "0.19.0"
paste = "1.0"
```
