### ISSUE TITLE
[bug] Tauri 2.0 cannot read environment changes to complete openssl cross compilation

### ISSUE THREAD

**Issue by Tlntin** [tauri-apps/tauri#6718]
### Describe the bug

I installed the 2.0 official tutorial and it worked fine. But when I added the openssl dependency in Cargo.toml, deleted the `gen` directory, ran `cargo tauri android init` and ran `cargo tauri android build`, an error was reported directly.

- Before
```toml
[dependencies]
tauri = { version = "2.0.0-alpha.8", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```
- after
```toml
[dependencies]
tauri = { version = "2.0.0-alpha.8", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
openssl-sys = "0.9"
openssl = "0.10"
serde_json = "1.0"
```

- Error stdout
```bash
--- stdout
  cargo:rerun-if-env-changed=AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR
  AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=AARCH64_LINUX_ANDROID_OPENSSL_INCLUDE_DIR
  AARCH64_LINUX_ANDROID_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=AARCH64_LINUX_ANDROID_OPENSSL_DIR
  AARCH64_LINUX_ANDROID_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
```
According to the openssl-sys documentation, i need to set cross-platform related variables. I installed openssl on multiple platforms with vcpkg, and then set the following variables.
```bash
# aarch64_linux_android
export AARCH64_LINUX_ANDROID_OPENSSL_DIR="xxx"
export AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR="xxx"
export AARCH64_LINUX_ANDROID_OPENSSL_INCLUDE_DIR="xxx"
# x86_64_linux_android
export X86_64_LINUX_ANDROID_OPENSSL_DIR="xxx"
export X86_64_LINUX_ANDROID_OPENSSL_LIB_DIR="xxx"
export X86_64_LINUX_ANDROID_OPENSSL_INCLUDE_DIR="xxx"
```

However, when I run `cargo tauri android dev` again, it still prompts me that these variables are not set. So I wrote them to `~/.bashrc`, `~/.zshrc`, `/etc/profile`, unfortunately it still took effect。

Then, I entered the `src-tauri` directory and tried to compile directly with this command: `cargo rustc --target=x86_64-linux-android`, it ran successfully, and the openssl related variables I set were displayed during compilation, Although the ld link libandroid and libc error is prompted at the end, it at least shows that it can read variables.

### Platform and versions

```text
$ cargo tauri info         
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.38.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.8
    - tauri-build [RUST]: 2.0.0-alpha.4
    - wry [RUST]: 0.27.3
    - tao [RUST]: 0.18.3
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.8

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```
