### ISSUE TITLE
[bug] cannot compile due to outdated fixed version of the time-crate (set at `=0.3.15`)

### ISSUE THREAD

**Issue by jgeluk** [tauri-apps/tauri#6973]
### Describe the bug

In the following tauri-crates there's a hard dependency to the `time` crate, set at version `=0.3.15`:

- `core/tauri`
- `core/tauri-codegen`
- `core/tauri/tests/app-updater`
- `tooling/bench`
- `tooling/bundler`

### Platform and versions

```text
Tauri version 1.3.0
```

**Comment by amrbashir** [comment]
fixed by https://github.com/tauri-apps/tauri/pull/6966

**Comment by FabianLars** [comment]
For a quick workaround without having to use tauri itself from git is to overwrite time's version with its git version by adding this to your cargo.toml file
```toml
[dependencies]
time = { git = "https://github.com/time-rs/time", rev = "v0.3.21" } # needed no matter if you use it as a direct dependency to prevent a cargo panic

[patch.crates-io]
time = { git = "https://github.com/time-rs/time", rev = "v0.3.21" }
```
