### ISSUE TITLE
Sidecar is not running after built

### ISSUE THREAD

**Issue by Siyer2** [tauri-apps/tauri#7250]
### Describe the bug

I have embedded external binaries (implemented following [this Tauri guide](https://tauri.app/v1/guides/building/sidecar)). The binaries are signed. I am able to successfully build and notarize the application. But when I open the application on Mac M2 computer, the binaries do not run. 

When I simply place the binaries in src-tauri/bin, I am able to run it locally using tauri-dev but it fails when I try with the Tauri action. 

### Reproduction

1. Create a Tauri application
2. In src-tauri/bin, deposit some binaries (I used qdrant-aarch64-apple-darwin, qdrant-x86_64-apple-darwin, qdrant-x86_64-pc-windows-msvc.exe, qdrant-x86_64-unknown-linux-gnu which can be downloaded from [here](https://github.com/qdrant/qdrant/releases/tag/v1.2.2) and `pkg` to make binaries from Nest.js. All binaries were signed)
4. In `tauri.conf.json`, in tauri->bundle->externalBin add `["bin/qdrant", "bin/server"]`
5. In `tauri.conf.json`, in tauri add this:
```
"allowlist": {
      "all": false,
      "shell": {
        "sidecar": true,
        "scope": [{ "name": "bin/server", "sidecar": true }]
      }
    },
```
7. Build the action with the Tauri action like this
```
- name: Build the app
        uses: tauri-apps/tauri-action@dev
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_PROVIDER_SHORT_NAME: ${{ secrets.APPLE_PROVIDER_SHORT_NAME }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'myapp v__VERSION__ for ${{ matrix.release-name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.rust-arch }}
```
5. After opening the dmg, the sidecars will not work. (Server and Qdrant will not run).

### Expected behavior

I expect the built app to work as it does locally using tauri-dev. 

### Platform and versions

```text
Environment
  › OS: Mac OS 13.3.1 X64
  › Node.js: 20.3.0
  › npm: 9.6.7
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3 (outdated, latest: 1.4.0)
  › @tauri-apps/api [NPM]: 1.2.0 (outdated, latest: 1.4.0)
  › tauri [RUST]: 1.3.0,
  › tauri-build [RUST]: 1.3.0,
  › tao [RUST]: 0.16.2,
  › wry [RUST]: 0.24.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src
```

### Stack trace

Output when I open the built app's `Contents/MacOS`
1. myapp: opens the frontend of the app (but without working sidecars)
2. qdrant: 
```
/Applications/myapp.app/Contents/MacOS/qdrant: line 1: version: command not found
/Applications/myapp.app/Contents/MacOS/qdrant: line 2: oid: command not found
__TEXT	__DATA	__OBJC	others	dec	hex
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size: can't open file: 48204932 (No such file or directory)

Saving session...completed.

[Process completed]
```
3. server:
```
/Applications/myapp.app/Contents/MacOS/server: line 1: version: command not found
/Applications/myapp.app/Contents/MacOS/server: line 2: oid: command not found
__TEXT	__DATA	__OBJC	others	dec	hex
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size: can't open file: 89516208 (No such file or directory)

Saving session...completed.

[Process completed]
```

**Comment by Siyer2** [comment]
The issue for me was that I was using git lfs. In my action, setting adding lfs: true worked:
```
- name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
```
