### ISSUE TITLE
[bug] Tauri-bundler Breaking Change in Minor Version  

### ISSUE THREAD

**Issue by ealmloff** [tauri-apps/tauri#7733]
### Describe the bug

The 1.3.0 version of tauri-bundler has breaking changes. Cargo considers this a non-breaking upgrade from 1.2.1 because the major version is `>1`.

### Reproduction

Here is a repo that reproduces the issue with a cargo.lock in the correct form: https://github.com/ealmloff/tauri-bundler-breaking

Or here is a inline version:

```toml
[package]
name = "tauri-bundler-breaking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# This build will succeed
# tauri-bundler = "=1.2.1"
# This will get resolved to 1.3.0 and fail to build
tauri-bundler = "1.2.1"
```

```rust
use std::collections::HashMap;

fn main() {
    tauri_bundler::DebianSettings {
        depends: None,
        files:HashMap::new(),
        // More fields are required in the 1.3.0 version of tauri-bundler
    };
}
```

### Expected behavior

Running cargo update should not break an application that depends on tauri-bundler 1.2.1

### Platform and versions

```text
rustc 1.72.0 (5680fa18f 2023-08-23)
Cargo resolver version 2
```

### Additional context

See https://github.com/DioxusLabs/dioxus/issues/1413 for the original discovery of this issue
