### ISSUE TITLE
[help] getting a basic example of using Tauri driver and testing invoked commands working

### ISSUE THREAD

**Issue by stephen-h-d** [tauri-apps/tauri#7830]
I am trying to test a full demo application with Selenium.  By "full" I mean not just the testing as demonstrated by the [Hello Tauri app](https://tauri.app/v1/guides/testing/webdriver/example/selenium) which references [this example code](https://github.com/chippers/hello_tauri) but instead something that invokes a command in Rust.  I am using the app I made by following [this tutorial](https://tauri.app/v1/guides/getting-started/setup/vite#invoke-commands), and it runs normally with cargo tauri dev --release, but when I try to test it with Mocha and Selenium, the application does not appear to start properly.  That is, the binary gets run, and it pops up a Tauri app that says "Could not connect: Connection refused".

I have two questions:  

1. Should it be possible to test a Tauri app with Selenium, including the invoking of Rust commands? 
2. If the answer to question 1 is "yes", do you know what I am doing wrong?  I made [this repo](https://github.com/stephen-h-d/tauri_driver_usage_demo) which contains all the relevant code.  I can provide more details if needed.

(I previously opened a support post in the Tauri Apps discord server but haven't gotten a response yet.)

**Comment by amosjyng** [comment]
Do you have the `custom-protocol` feature enabled on your Tauri project? For me, it worked when I tried changing

```toml
[dependencies]
tauri = { version = "1.4", features = [..., "process-command-api"] }
...

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
...
```

to

```toml
[dependencies]
tauri = { version = "1.4", features = [ ..., "custom-protocol"] }
...

[features]
# this is necessary to prevent the Tauri CLI from complaining about the lack of a
# custom-protocol feature during compilation
custom-protocol = []
```
