### ISSUE TITLE
`tauri` dependency features on the `Cargo.toml` file does not match the allowlist defined

### ISSUE THREAD

**Issue by VirxEC** [tauri-apps/tauri#7940]
### Describe the bug

For my app I have different features activated depending on whether the app is being built on Windows or Linux/MacOS. It used to work around Tauri 1.2 but no longer in Tauri 1.5.1.

This is in my `Cargo.toml`:
```toml
[target.'cfg(not(any(windows, target_os = "macos")))'.dependencies.tauri]
version = "1.5.0"
features = ["devtools", "dialog", "reqwest-client", "shell-open", "reqwest-native-tls-vendored"]
 
[target.'cfg(any(windows, target_os = "macos"))'.dependencies.tauri]
version = "1.5.0"
features = ["devtools", "dialog", "reqwest-client", "shell-open", "updater"]
```
The problem is that I only specify `updater` as being active in `tauri.windows.conf.json` - because that's the only time I want it. But Tauri doesn't like that - I get the following error message along with the app not building:
> The `tauri` dependency features on the `Cargo.toml` file does not match the allowlist defined under `tauri.conf.json`.

When I DO run `cargo tauri dev` like it tells me to, it adds the `reqwest-native-tls-vendored` to Windows and removes the `updater` feature from Windows.

When I instead put this in `Cargo.toml`:
```toml
[target.'cfg(any(windows, target_os = "macos"))'.dependencies.tauri]
version = "1.5.0"
features = ["devtools", "dialog", "reqwest-client", "shell-open", "updater"]

[target.'cfg(not(any(windows, target_os = "macos")))'.dependencies.tauri]
version = "1.5.0"
features = ["devtools", "dialog", "reqwest-client", "shell-open", "reqwest-native-tls-vendored"]
```
Then only the `updater` feature gets removed when I run `cargo tauri dev` and `reqwest-native-tls-vendored` stays as being Linux only.

### Reproduction

Something simple like this:

`Cargo.toml`:
```toml
[target.'cfg(not(any(windows, target_os = "macos")))'.dependencies.tauri]
version = "1.5.0"
features = ["reqwest-native-tls-vendored"]

[target.'cfg(any(windows, target_os = "macos"))'.dependencies.tauri]
version = "1.5.0"
features = ["updater"]
```

`tauri.conf.json`:
```json
{
  "tauri": {
    "comment": "other app info here",
    "updater": {
      "active": false,
    }
  }
}
```

`tauri.windows.conf.json`:
```json
{
  "tauri": {
    "updater": {
      "active": true,
      "comment": "other updater info here",
    }
  }
}
```

Should be enough to trigger the bug upon trying to build.

### Expected behavior

The app should just build successfully and work.

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 23.04 X64
    ✔ webkit2gtk-4.0: 2.40.5
    ✔ rsvg2: 2.54.5
    ✔ rustc: 1.73.0-beta.8 (975e63fed 2023-09-29)
    ✔ Cargo: 1.73.0-beta.8 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: beta-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.13.0
    - npm: 9.2.0

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: 1.5.1
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.5.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../assets
    - devPath: http://localhost:5500/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

```text
error: failed to run custom build command for `my-app v1.0.47 (/home/virx/Documents/my-app/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/virx/Documents/my-app/src-tauri/target/debug/build/my-app-16e4fe7e44bc5a4c/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop

        The `tauri` dependency features on the `Cargo.toml` file does not match the allowlist defined under `tauri.conf.json`.
        Please run `tauri dev` or `tauri build` or remove the `updater` feature.
      
warning: build failed, waiting for other jobs to finish...
```
