### ISSUE TITLE
[bug] window height is not correct

### ISSUE THREAD

**Issue by seongs1024** [tauri-apps/tauri#8034]
### Describe the bug

The element cannot occupy by the height of the window when it changed to the full screen window.

![image](https://github.com/tauri-apps/tauri/assets/56729421/7425e814-8d24-4c77-ba90-ffc3a37e9e01)

However after the inspection window is showed up, it can occupy by the whole screen.

![image](https://github.com/tauri-apps/tauri/assets/56729421/ab3655dd-3b79-4e68-9a48-c390ba3a0a08)

### Reproduction

`src/App.tsx`
```ts
import { createSignal } from "solid-js";
import logo from "./assets/logo.svg";
import { invoke } from "@tauri-apps/api/tauri";
import "./App.css";

function App() {
  return (
    <header class="header">
    </header>
  );
}

export default App;
```

`src/style.css`
```css
.header {
  background-color: #282c34;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}
```

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 10.15.7 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0-nightly (49691b1f7 2023-10-16)
    ✔ Cargo: 1.75.0-nightly (6fa6fdc76 2023-10-10)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-apple-darwin (default)
    - node: 18.18.2
    - pnpm: 8.9.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: 1.5.3
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.2

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by seongs1024** [comment]
For this situation, the bottom of window looked like margined because the top position might go a little bit up.
Whenever I try, the top also seems to be margined sometimes...

**Comment by pewsheen** [comment]
Could you try adding this to your `src/style.css` and see if it works?
```css
body {
  margin: 0;
}
```
