### ISSUE TITLE
[bug] Uncaught TypeError: Cannot read properties of `undefined` (reading 'os')

### ISSUE THREAD

**Issue by bug4you** [tauri-apps/tauri#8212]
### Describe the bug

I did the project as shown in the [docs](https://beta.tauri.app/features/os-info/#setup), but this error is appearing in the browser console.

![image](https://github.com/tauri-apps/tauri/assets/140431027/aa52d027-d474-4429-9399-9d815d920372)

### Reproduction

This happened when I added to the project

```rust
// This is the part where the plugin is added to the main function
fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_window::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_os::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 119.0.2151.44
    ✔ MSVC: Visual Studio Build Tools 2019
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - yarn: 1.22.19
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.17
    - tauri-build [RUST]: 2.0.0-alpha.11
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.11
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.17

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
Done in 10.90s.
```

### Stack trace

```text
Uncaught TypeError: Cannot read properties of undefined (reading 'os')
    at <anonymous>:325:18
    at <anonymous>:326:4
    at <anonymous>:387:3
```

**Comment by FabianLars** [comment]
Hi :)

Can you also share the version of the plugin listed in cargo.toml and package.json? And then also your js code please.
Just to make sure everything was set up correctly and that we can try to reproduce it with the same setup.

**Comment by bug4you** [comment]
Hello of course ;-)

`Cargo.toml`
```toml
[package]
name = "tauri-app"
version = "0.0.1"
description = "A Tauri App"
authors = ["Dilshod Fayzullayev"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-alpha", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha", features = [] }
tauri-plugin-window = "2.0.0-alpha"
tauri-plugin-shell = "2.0.0-alpha"
serde_json = "1.0"
tauri-plugin-os = "2.0.0-alpha.4"
tauri-plugin-notification = "2.0.0-alpha.5"
tauri-plugin-process = "2.0.0-alpha"
home = "0.5.5"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
```

`package.json`
```json
{
  "name": "tauri-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "tauri": "tauri"
  },
  "dependencies": {
    "@fontsource-variable/comfortaa": "^5.0.17",
    "@tauri-apps/api": "^2.0.0-alpha.11",
    "@tauri-apps/plugin-notification": "^2.0.0-alpha.3",
    "@tauri-apps/plugin-os": "^2.0.0-alpha.4",
    "@tauri-apps/plugin-process": "^2.0.0-alpha.3",
    "@tauri-apps/plugin-shell": "^2.0.0-alpha.3",
    "halfmoon": "^2.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "reactstrap": "^9.2.1"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^2.0.0-alpha.17",
    "@vitejs/plugin-react": "^4.0.3",
    "vite": "^4.4.4"
  }
}
```

`main.rs`
```rust
// This is the part where the plugin is added to the main function
fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_window::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_os::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
