### ISSUE TITLE
[bug] An error occurred: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }

### ISSUE THREAD

**Issue by bug4you** [tauri-apps/tauri#8340]
### Describe the bug

I was supposed to add my tauri program to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` in the `Registry` so that it will run automatically when `Windows` restarts, but I get an error

![image](https://github.com/tauri-apps/tauri/assets/140431027/1d15c4ca-911c-449f-b8f1-3cb2094330ec)

### `main.rs`
```rust
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod regedit;

use regedit::registry::registry;

// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[tauri::command]
fn registry_init() {
    let result = registry();
    if result.is_ok() {
        println!("Success");
    } else if result.is_err() {
        result.expect("An error occurred")
    }
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet, registry_init])
        .run(tauri::generate_context!())
        .expect("WTF: error while running tauri application");
}
```

### `registry.rs`

```rust
use std::ffi::OsString;
use std::io;
use std::path::Path;

use winreg::enums::*;
use winreg::RegKey;

pub(crate) fn registry() -> io::Result<()> {
    let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);

    let path: OsString = Path::new("SOFTWARE").join("Microsoft").join("Windows").join("CurrentVersion").join("Run").into();

    let (key, disp) = hklm.create_subkey(path)?;

    match disp {
        REG_CREATED_NEW_KEY => println!("A new key has been created"),
        REG_OPENED_EXISTING_KEY => println!("An existing key has been opened"),
    }

    key.set_value("TestBackgroundApp", &"This will be the current location of the program")?;
    let sz_val: String = key.get_value("TestBackgroundApp")?;
    println!("TestBackgroundApp = {}", sz_val);
    Ok(())
}
```

### `tauri.conf.json`

> I have added any permissions that may be needed

```json
{
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist"
  },
  "package": {
    "productName": "test-background-process-app",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": true,
      "shell": {
        "all": true,
        "open": true
      },
      "os": {
        "all": true
      },
      "app": {
        "all": true,
        "show": true,
        "hide": true
      }
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "test-background-process-app",
        "width": 800,
        "height": 600
      }
    ]
  }
}
```

### `Cargo.toml`

> I added a library called winreg to my project

```toml
[package]
name = "test-background-process-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
winreg = "0.52"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
```

### App.jsx

```jsx
import React, {useMemo} from 'react';
import {invoke} from "@tauri-apps/api/tauri";

const App = () => {
    useMemo(async () => {
        try {
            await invoke("registry_init");
        } catch (e) {
            console.log("ERROR: ", e)
        }
    }, []);

    return (
        <div>
            <h1>Dastur ishga tushdi</h1>
        </div>
    );
};

export default App;
```

### The result I expected should be something like this

![image](https://github.com/tauri-apps/tauri/assets/140431027/8d831dac-9117-4e0f-bc68-5fea7d7311ef)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 119.0.2151.97
    ✔ MSVC: Visual Studio Build Tools�2019
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.7

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
Done in 11.83s.
```
