### ISSUE TITLE
[bug] beta autogenerate permissions for plugins

### ISSUE THREAD

**Issue by keeganstothert** [tauri-apps/tauri#8872]
### Describe the bug

The autogenerate permissions only appears to work with snake case command names, this is fine for any custom commands but is incompatible when trying to call out to the mobile `Plugin` class methods (ios & android base class). These are all camel case `checkPermissions` `requestPermissions` etc.

in order to solve this for now I had to first populate the `build.rs` with

```rust
const COMMANDS: &[&str] = &["get_location", "check_permissions", "request_permissions"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
```

then run `cargo build` to generate the permissions, then remove the commands to prevent the autogenerated files from being overwritten

```rust
const COMMANDS: &[&str] = &[];
```

then I manually changed the autogenerated `permissions/autogenerated/commands/check_permissions.toml`

```toml
# Automatically generated - DO NOT EDIT!

"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-check-permissions"
description = "Enables the check_permissions command without any pre-configured scope."
commands.allow = ["checkPermissions"] <- change to camelcase

[[permission]]
identifier = "deny-check-permissions"
description = "Denies the check_permissions command without any pre-configured scope."
commands.deny = ["checkPermissions"] <- change to camelcase
```

### Expected behavior

remove the snake case requirement and be more flexible in how the permissions are generated OR provide a detailed guide on how users can create their own permissions without using the autogenerate.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.19.0
    - npm: 10.2.3

[-] Packages
    - tauri-cli [RUST]: 2.0.0-beta.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
```

### Additional context

https://discord.com/channels/616186924390023171/1207460554940358696
