### ISSUE TITLE
[bug] Ubuntu 22.04, Tauri Beta, All Dependencies Installed, `tauri dev` Fail to Compile: gdk-sys, glib-sys, gobject-sys, pango-sys, gio-sys, cairo-sys-rs, gdk-pixbuf-sys, atk-sys

### ISSUE THREAD

**Issue by Saplyn** [tauri-apps/tauri#9093]
### Describe the bug

When running `cargo tauri dev`, the compilation fails with the following packages failed to compile:

```
error: failed to run custom build command for `gdk-sys v0.18.0`
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `glib-sys v0.18.1`
error: failed to run custom build command for `gobject-sys v0.18.0`
error: failed to run custom build command for `pango-sys v0.18.0`
error: failed to run custom build command for `gio-sys v0.18.1`
error: failed to run custom build command for `cairo-sys-rs v0.18.2`
error: failed to run custom build command for `gdk-pixbuf-sys v0.18.0`
error: failed to run custom build command for `atk-sys v0.18.0`
```

saying that:

```
  The system library `gdk-3.0` required by crate `gdk-sys` was not found.
  The system library `glib-2.0` required by crate `glib-sys` was not found.
  The system library `gobject-2.0` required by crate `gobject-sys` was not found.
  The system library `pango` required by crate `pango-sys` was not found.
  The system library `gio-2.0` required by crate `gio-sys` was not found.
  The system library `cairo` required by crate `cairo-sys-rs` was not found.
  The system library `gdk-pixbuf-2.0` required by crate `gdk-pixbuf-sys` was not found.
  The system library `atk` required by crate `atk-sys` was not found.
```

But I am sure that I have installed both [v1](https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux) and [v2 dependencies](https://beta.tauri.app/guides/prerequisites/).

### Reproduction

The `src-tauri/Cargo.toml`

```toml
[package]
name = "prj_grid"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "^2.0.0-beta", features = [] }

[dependencies]
# Tauri Essentials
tauri = { version = "^2.0.0-beta", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Tauri Plugins
tauri-plugin-shell = "^2.0.0-beta"
tauri-plugin-window-state = "^2.0.0-beta"
tauri-plugin-store = "^2.0.0-beta"
# Logging
log = "0.4"
simplelog = "0.12"
# Utilities
time = { version = "0.3", features = ["serde"] }
directories = "5.0"
thiserror = "1.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "grid_lib"
crate-type = ["staticlib", "cdylib", "rlib", "lib"]
```

The `Cargo.toml`

```toml
[package]
name = "prj_grid-ui"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Leptos Essential
leptos = { version = "0.6", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
console_error_panic_hook = "0.1"
# Logging
console_log = { version = "1.0", features = ["color"] }
log = "0.4"
# Utilities
serde_json = "1.0"

[workspace]
members = ["src-tauri"]
```

And run `cargo tauri dev`, and then fail.

### Expected behavior

It should not fail to compile. (qwq)

### Full `tauri info` output

```text
WARNING: no lock files found, defaulting to npm

[✘] Environment
    - OS: Ubuntu 22.04 X64
    ✘ webkit2gtk-4.1: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✘ rsvg2: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.1
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - tauri-cli [RUST]: 2.0.0-beta.6
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

### Additional context

I think I have installed `webkit2gtk-4.1` and `rsvg2`, because `sudo apt install libwebkit2gtk-4.1-dev librsvg2-dev` says:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
librsvg2-dev is already the newest version (2.52.5+dfsg-3ubuntu0.2).
libwebkit2gtk-4.1-dev is already the newest version (2.42.5-0ubuntu0.22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Am I missing some steps to set them up?
