### ISSUE TITLE
[bug] [2.0] Cyclic package dependency: package `getrandom v0.2.12` when adding `surrealdb v1.2.2` as dependency

### ISSUE THREAD

**Issue by vsavovski** [tauri-apps/tauri#9150]
### Describe the bug

```toml
[package]
name = "test-ui"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.5", features = ["csr"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
surrealdb = {version = "1.2.2", features=["kv-mem"]}

[workspace]
members = ["src-tauri"]

```

```
❯ cargo update
    Updating crates.io index
error: cyclic package dependency: package `getrandom v0.2.12` depends on itself. Cycle:
package `getrandom v0.2.12`
    ... which satisfies dependency `getrandom = "^0.2.7"` of package `ahash v0.8.11`
    ... which satisfies dependency `ahash = "^0.8.6"` of package `hashbrown v0.14.3`
    ... which satisfies dependency `hashbrown = "^0.14.1"` of package `indexmap v2.2.5`
    ... which satisfies dependency `indexmap = "^2.2.1"` of package `serde_json v1.0.114`
    ... which satisfies dependency `serde_json = "^1.0"` of package `wasm-bindgen v0.2.92`
    ... which satisfies dependency `wasm-bindgen = "^0.2.92"` of package `js-sys v0.3.69`
    ... which satisfies dependency `js-sys = "^0.3"` of package `getrandom v0.2.12`
    ... which satisfies dependency `getrandom = "^0.2.3"` of package `ahash v0.7.8`
```

### Reproduction

```
❯ cargo create-tauri-app --beta
```
```
✔ Project name · test
✔ Choose which language to use for your frontend · Rust - (cargo)
✔ Choose your UI template · Leptos - (https://leptos.dev/)
✔ Would you like to setup the project for mobile as well? · yes
```
```
❯ cargo add surrealdb --features kv-mem
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.17.0
    - pnpm: 7.28.0
    - yarn: 1.22.19
    - npm: 8.15.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.10
    - tauri-build [RUST]: 2.0.0-beta.8
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - tauri-cli [RUST]: 2.0.0-beta.8
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.8

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```
