### ISSUE TITLE
[bug] Android os error 2 with sidecar

### ISSUE THREAD

**Issue by lindongchen** [tauri-apps/tauri#9774]
### Describe the bug

**Error**: Uncaught (in promise) No such file or directory (os error 2)
**Event**: Command.sidecar("bin/pipy", args)  ...call sidecar
**Sidecar position:** src-tauri/bin/pipy-aarch64-linux-android
**Sidecar package** position: src-tauri/target/aarch64-linux-android/debug/pipy
**Sidecar bundle:** tauri.conf.json => bundle > "externalBin": ["bin/pipy"]

Simply put, I saw that the sidecar had been packaged in a reasonable location, but when running on the Android emulator, I couldn't find the file. What I can confirm is that other programs can run as usual, and on Mac OS and Windows, my sidecar still works as usual, but it can't be found on the Android emulator

Here is my Cargo.toml configuration：
```toml
[lib]
name = "ztm_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

# tauri = { version = "2.0.0-beta", features = ["devtools"] }
[dependencies]
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }
tauri = { version = "=2.0.0-beta.19", features = [] }
tauri-plugin-shell = "2.0.0-beta.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-process = "2.0.0-beta.3"
tauri-plugin-http = "2.0.0-beta.3"
tauri-plugin-os = "2.0.0-beta.3"
tauri-plugin-fs = "=2.0.0-beta.7"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-cli = "2.0.0-beta"

[target.'cfg(any(target_os = "android"))']
linker = "~/Library/Android/sdk/ndk/27.0.11718014/toolchains/llvm/prebuilt/darwin-x86_64/bin"
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 12.0.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.7.1
    - pnpm: 8.10.5
    - yarn: 1.22.17
    - npm: 6.14.17

[-] Packages
    - tauri [RUST]: 2.0.0-beta.19
    - tauri-build [RUST]: 2.0.0-beta.15
    - wry [RUST]: 0.39.5
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.17

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../../agent/gui
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```
